/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Receptionist;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahmoud160312
 */
public class Appointment1 extends javax.swing.JFrame {

    /**
     * Creates new form Appointment
     */
    public Appointment1() {
        initComponents();
        CenteredFrame(this);
    }
     public void CenteredFrame(javax.swing.JFrame objFrame){
           Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY); 
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        spcialist = new javax.swing.JLabel();
        jtextfieldspecialist = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtextfieldsecond_name = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtextfieldfirst_name = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_doctor = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        spcialist.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        spcialist.setForeground(new java.awt.Color(0, 153, 204));
        spcialist.setText("Specialist");
        jPanel5.add(spcialist);
        spcialist.setBounds(350, 540, 130, 30);

        jtextfieldspecialist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldspecialistActionPerformed(evt);
            }
        });
        jPanel5.add(jtextfieldspecialist);
        jtextfieldspecialist.setBounds(500, 540, 160, 30);

        jLabel16.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 204));
        jLabel16.setText("Second name");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(350, 500, 130, 30);

        jtextfieldsecond_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldsecond_nameActionPerformed(evt);
            }
        });
        jPanel5.add(jtextfieldsecond_name);
        jtextfieldsecond_name.setBounds(500, 500, 160, 30);

        jLabel15.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 204));
        jLabel15.setText("         Doctor Name is :-");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(400, 420, 220, 30);

        jtextfieldfirst_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfieldfirst_nameActionPerformed(evt);
            }
        });
        jPanel5.add(jtextfieldfirst_name);
        jtextfieldfirst_name.setBounds(500, 460, 160, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 204));
        jLabel14.setText("First name");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(350, 460, 130, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 204));
        jLabel13.setText("Appointment ID:");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(10, 450, 130, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField3);
        jTextField3.setBounds(150, 450, 140, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 204));
        jButton3.setText("Search");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(140, 510, 153, 42);

        jButton23.setBackground(new java.awt.Color(255, 255, 255));
        jButton23.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton23.setForeground(new java.awt.Color(0, 153, 204));
        jButton23.setText("load");
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton23);
        jButton23.setBounds(750, 510, 153, 42);

        table_doctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Appointmentt ID", "Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_doctor);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(0, 166, 930, 460);

        jPanel10.setBackground(new java.awt.Color(0, 153, 204));
        jPanel10.setLayout(null);

        jLabel61.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("View Appointment");
        jPanel10.add(jLabel61);
        jLabel61.setBounds(40, 0, 220, 70);

        jLabel62.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("Logout");
        jLabel62.setToolTipText("");
        jLabel62.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        jLabel62.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel62KeyPressed(evt);
            }
        });
        jPanel10.add(jLabel62);
        jLabel62.setBounds(830, 50, 50, 20);

        jLabel63.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Home");
        jLabel63.setToolTipText("");
        jLabel63.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel63MouseClicked(evt);
            }
        });
        jLabel63.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel63KeyPressed(evt);
            }
        });
        jPanel10.add(jLabel63);
        jLabel63.setBounds(780, 50, 50, 20);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton13);
        jButton13.setBounds(790, 20, 30, 30);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton14);
        jButton14.setBounds(840, 20, 30, 30);

        jPanel5.add(jPanel10);
        jPanel10.setBounds(10, 50, 910, 70);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(420, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 17, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 17, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel62MouseClicked

    private void jLabel62KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel62KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel62KeyPressed

    private void jLabel63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel63MouseClicked

    private void jLabel63KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel63KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel63KeyPressed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            ReceptionistPortal f=new ReceptionistPortal();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            ReceptionistLoginForm f = new ReceptionistLoginForm();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed

        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select appointment_id,adate,atime  from appointment");

            ResultSet set = stmt.executeQuery();

            DefaultTableModel dm = new DefaultTableModel();

            dm.addColumn("appointment_id");
            dm.addColumn("adate");
            dm.addColumn("atime");
            
            while (set.next()) {

                String r[] = {set.getString(1), set.getString(2),
                    set.getString(3)
                };
                dm.addRow(r);
            }
            table_doctor.setModel(dm);

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
         try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select doctor.first_name ,doctor.second_name,doctor.specialist  from doctor,appointment where doctor.doctor_id=appointment.doctor_id\n" +
"  and appointment.appointment_id=? ");

           

            String check_id;
            check_id = jTextField3.getText();

            String first_name = "", second_name = "",specialist="";

            stmt.setString(1, check_id);
            
            ResultSet set = stmt.executeQuery();
           while (set.next()) {
                 first_name=set.getString("first_name");
                 second_name=set.getString("second_name");
                   specialist=set.getString("specialist");
            }
           
           jtextfieldfirst_name.setText(first_name);
           jtextfieldsecond_name.setText(second_name);
           jtextfieldspecialist.setText(specialist);
              } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }



      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jtextfieldfirst_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldfirst_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldfirst_nameActionPerformed

    private void jtextfieldsecond_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldsecond_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldsecond_nameActionPerformed

    private void jtextfieldspecialistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfieldspecialistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfieldspecialistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appointment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appointment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appointment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appointment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appointment1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jtextfieldfirst_name;
    private javax.swing.JTextField jtextfieldsecond_name;
    private javax.swing.JTextField jtextfieldspecialist;
    private javax.swing.JLabel spcialist;
    private javax.swing.JTable table_doctor;
    // End of variables declaration//GEN-END:variables
}
