/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Receptionist;

import Doctor.*;
import admin.*;
import admin.AdminPortal;
import admin.AdminLoginForm;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mahmoud160312
 */
public class ChangeReceptionistPassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangeAdminUsernameAndPassword
     */
    public ChangeReceptionistPassword() {
        initComponents();
         jLabel3.setVisible(false);
         jLabel2.setVisible(false);
         jLabel8.setVisible(false);
        CenteredFrame(this);
    }

    public void CenteredFrame(javax.swing.JFrame objFrame) {
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Change = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newusertextfield1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        currentfield = new javax.swing.JPasswordField();
        newpassfield = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<<");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 10, 24, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        Change.setBackground(new java.awt.Color(0, 153, 204));
        Change.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Change.setForeground(new java.awt.Color(255, 255, 255));
        Change.setText("Change");
        Change.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeActionPerformed(evt);
            }
        });
        jPanel2.add(Change);
        Change.setBounds(120, 220, 127, 39);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("New Password");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 150, 122, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("Current Password");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 90, 133, 30);

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Current password is wrong");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 120, 160, 20);

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("user name  must have a value");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(170, 60, 170, 20);

        newusertextfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newusertextfield1ActionPerformed(evt);
            }
        });
        jPanel2.add(newusertextfield1);
        newusertextfield1.setBounds(160, 30, 180, 30);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("ID Code");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 30, 90, 30);

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("password must have a value");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(170, 180, 160, 20);
        jPanel2.add(currentfield);
        currentfield.setBounds(160, 90, 180, 30);
        jPanel2.add(newpassfield);
        newpassfield.setBounds(160, 150, 180, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 170, 360, 290);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/change the password photo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 360, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeActionPerformed
        {
          
            if ("".equals(newpassfield.getText())) {
                jLabel8.setVisible(true);
            }
            if ("".equals(newusertextfield1.getText())) {
                jLabel2.setVisible(true);
               
            }
            else if(!"".equals(currentfield.getText())&&!"".equals(newpassfield.getText())&&!"".equals(newusertextfield1.getText()))  
            {     
            try {
            java.sql.Connection  con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
             PreparedStatement stmt = con.prepareStatement("select *from  receptionist ");
            PreparedStatement stmt2 = con.prepareStatement("update receptionist set Rpassword=? where receptionist_id=?");
             
             ResultSet set = stmt.executeQuery();
    
             String  username="", currentpass="",newpass="",checkfromdata="",checkuser="";
            
            currentpass = currentfield.getText();
            newpass=newpassfield.getText();
            username=newusertextfield1.getText();
            
           
            int mcurrentpass=Integer.parseInt(currentpass);
             int mnewpass=Integer.parseInt(newpass);
             int musername=Integer.parseInt(username);
            
             
             while (set.next()){
             checkuser=set.getString("receptionist_id");
             checkfromdata=set.getString("Rpassword");
            
             
             if(checkuser.equals(username)&&checkfromdata.equals(currentpass)){
                 
                //***************execute update ***************
                    stmt2.setInt(1, mnewpass); 
                    stmt2.setInt(2, musername);
                    stmt2.executeUpdate();
                 break;
            }
             
             }
            
            if (checkuser.equals(username)&&checkfromdata.equals(currentpass)) {
                
      
                JOptionPane.showMessageDialog(this,"Your password saved Successfully :)","Confim",JOptionPane.INFORMATION_MESSAGE);
                newusertextfield1.setText("");
                currentfield.setText("");
                newpassfield.setText("");
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                jLabel8.setVisible(false);
            }
            else {
                jLabel3.setVisible(true);
                 jLabel2.setVisible(false);
                   jLabel8.setVisible(false);
            } 
            } catch (SQLException ex) {
          System.out.println("Error"+ex.getErrorCode());
            
            }
            
            
            }
            
        }
    }//GEN-LAST:event_ChangeActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        ReceptionistPortal f = new ReceptionistPortal();
        this.setVisible(false);
        f.setVisible(true);

    }//GEN-LAST:event_jLabel7MouseClicked

    private void newusertextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newusertextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newusertextfield1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeReceptionistPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeReceptionistPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeReceptionistPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeReceptionistPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeReceptionistPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Change;
    private javax.swing.JPasswordField currentfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField newpassfield;
    private javax.swing.JTextField newusertextfield1;
    // End of variables declaration//GEN-END:variables
}
