/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doctor;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahmoud160312
 */
public class Appointment extends javax.swing.JFrame {

    /**
     * Creates new form Appointment
     */
    public Appointment() {
        initComponents();
        CenteredFrame(this);
    }

    public void CenteredFrame(javax.swing.JFrame objFrame) {
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(0, 153, 204));
        jPanel6.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Appointment");
        jPanel6.add(jLabel1);
        jLabel1.setBounds(50, 0, 190, 70);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Logout");
        jLabel12.setToolTipText("");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jLabel12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel12KeyPressed(evt);
            }
        });
        jPanel6.add(jLabel12);
        jLabel12.setBounds(830, 50, 50, 20);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Home");
        jLabel15.setToolTipText("");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jLabel15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel15KeyPressed(evt);
            }
        });
        jPanel6.add(jLabel15);
        jLabel15.setBounds(780, 50, 50, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(790, 20, 30, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(840, 20, 30, 30);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(10, 50, 886, 70);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 204));
        jButton3.setText("Add");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(727, 164, 153, 42);

        jLabel23.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 204));
        jLabel23.setText("Doctor ID: ");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(70, 230, 140, 30);

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField13);
        jTextField13.setBounds(240, 350, 190, 30);

        jLabel24.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 153, 204));
        jLabel24.setText("Date:");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(70, 290, 110, 30);
        jPanel1.add(jTextField14);
        jTextField14.setBounds(240, 230, 190, 30);

        jLabel25.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 204));
        jLabel25.setText("Time:");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(70, 350, 110, 30);
        jPanel1.add(jTextField15);
        jTextField15.setBounds(240, 290, 190, 30);

        jLabel26.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 153, 204));
        jLabel26.setText("Appointment ID: ");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(70, 170, 140, 30);

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField16);
        jTextField16.setBounds(240, 170, 190, 30);

        jTabbedPane2.addTab("Add Appointment", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(0, 153, 204));
        jPanel7.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Update Appointment");
        jPanel7.add(jLabel28);
        jLabel28.setBounds(50, 0, 220, 70);

        jLabel29.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Logout");
        jLabel29.setToolTipText("");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jLabel29.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel29KeyPressed(evt);
            }
        });
        jPanel7.add(jLabel29);
        jLabel29.setBounds(830, 50, 50, 20);

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Home");
        jLabel30.setToolTipText("");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jLabel30.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel30KeyPressed(evt);
            }
        });
        jPanel7.add(jLabel30);
        jLabel30.setBounds(780, 50, 50, 20);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4);
        jButton4.setBounds(790, 20, 30, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5);
        jButton5.setBounds(840, 20, 30, 30);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(10, 50, 886, 70);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 153, 204));
        jButton6.setText("Update");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(440, 240, 153, 42);

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 153, 204));
        jButton16.setText("Search");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16);
        jButton16.setBounds(440, 170, 153, 42);

        jLabel13.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 204));
        jLabel13.setText("Date:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(70, 220, 110, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 204));
        jLabel14.setText("Appointment ID: ");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(70, 170, 140, 30);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(210, 170, 190, 30);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(210, 220, 190, 30);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(210, 280, 190, 30);

        jLabel16.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 204));
        jLabel16.setText("Time:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(70, 280, 110, 30);

        jTabbedPane2.addTab("Update Appointment", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(0, 153, 204));
        jPanel8.setLayout(null);

        jLabel43.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Delete Appointment");
        jPanel8.add(jLabel43);
        jLabel43.setBounds(50, 0, 210, 70);

        jLabel44.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Logout");
        jLabel44.setToolTipText("");
        jLabel44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        jLabel44.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel44KeyPressed(evt);
            }
        });
        jPanel8.add(jLabel44);
        jLabel44.setBounds(830, 50, 50, 20);

        jLabel45.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Home");
        jLabel45.setToolTipText("");
        jLabel45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        jLabel45.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel45KeyPressed(evt);
            }
        });
        jPanel8.add(jLabel45);
        jLabel45.setBounds(780, 50, 50, 20);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton7);
        jButton7.setBounds(790, 20, 30, 30);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton8);
        jButton8.setBounds(840, 20, 30, 30);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(10, 50, 886, 70);

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jButton17.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 153, 204));
        jButton17.setText("Search");
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton17);
        jButton17.setBounds(440, 170, 153, 42);
        jPanel3.add(jTextField7);
        jTextField7.setBounds(210, 170, 190, 30);

        jLabel17.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 204));
        jLabel17.setText("Appointment ID: ");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(70, 170, 140, 30);

        jLabel18.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 204));
        jLabel18.setText("Date:");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(70, 220, 110, 30);

        jLabel19.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 204));
        jLabel19.setText("Time:");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(70, 280, 110, 30);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(210, 220, 190, 30);
        jPanel3.add(jTextField9);
        jTextField9.setBounds(210, 280, 190, 30);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 153, 204));
        jButton9.setText("Delete");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);
        jButton9.setBounds(440, 240, 153, 42);

        jTabbedPane2.addTab("Delete Appointment", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(0, 153, 204));
        jPanel9.setLayout(null);

        jLabel58.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Search Appointment");
        jPanel9.add(jLabel58);
        jLabel58.setBounds(50, 0, 220, 70);

        jLabel59.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Logout");
        jLabel59.setToolTipText("");
        jLabel59.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel59MouseClicked(evt);
            }
        });
        jLabel59.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel59KeyPressed(evt);
            }
        });
        jPanel9.add(jLabel59);
        jLabel59.setBounds(830, 50, 50, 20);

        jLabel60.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("Home");
        jLabel60.setToolTipText("");
        jLabel60.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });
        jLabel60.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel60KeyPressed(evt);
            }
        });
        jPanel9.add(jLabel60);
        jLabel60.setBounds(780, 50, 50, 20);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton10);
        jButton10.setBounds(790, 20, 30, 30);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton11);
        jButton11.setBounds(840, 20, 30, 30);

        jPanel4.add(jPanel9);
        jPanel9.setBounds(10, 50, 886, 70);

        jLabel20.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 204));
        jLabel20.setText("Appointment ID: ");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(70, 170, 140, 30);

        jLabel21.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 204));
        jLabel21.setText("Date:");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(70, 220, 110, 30);

        jLabel22.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 204));
        jLabel22.setText("Time:");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(70, 280, 110, 30);
        jPanel4.add(jTextField10);
        jTextField10.setBounds(210, 280, 190, 30);
        jPanel4.add(jTextField11);
        jTextField11.setBounds(210, 220, 190, 30);
        jPanel4.add(jTextField12);
        jTextField12.setBounds(210, 170, 190, 30);

        jButton18.setBackground(new java.awt.Color(255, 255, 255));
        jButton18.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 153, 204));
        jButton18.setText("Search");
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton18);
        jButton18.setBounds(440, 170, 153, 42);

        jTabbedPane2.addTab("Search Appointment", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setText("Load");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton12);
        jButton12.setBounds(410, 410, 110, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Appointmentt ID", "Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(0, 130, 940, 400);

        jPanel10.setBackground(new java.awt.Color(0, 153, 204));
        jPanel10.setLayout(null);

        jLabel61.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("View Appointment");
        jPanel10.add(jLabel61);
        jLabel61.setBounds(50, 0, 200, 70);

        jLabel62.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("Logout");
        jLabel62.setToolTipText("");
        jLabel62.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        jLabel62.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel62KeyPressed(evt);
            }
        });
        jPanel10.add(jLabel62);
        jLabel62.setBounds(830, 50, 50, 20);

        jLabel63.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Home");
        jLabel63.setToolTipText("");
        jLabel63.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel63MouseClicked(evt);
            }
        });
        jLabel63.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel63KeyPressed(evt);
            }
        });
        jPanel10.add(jLabel63);
        jLabel63.setBounds(780, 50, 50, 20);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton13);
        jButton13.setBounds(790, 20, 30, 30);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton14);
        jButton14.setBounds(840, 20, 30, 30);

        jPanel5.add(jPanel10);
        jPanel10.setBounds(10, 50, 910, 70);

        jTabbedPane2.addTab("View Appointment", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel12KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12KeyPressed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel15KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            DoctorPortal f = new DoctorPortal();
            this.setVisible(false);
            f.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            DoctorLoginForm f = new DoctorLoginForm();
            this.setVisible(false);
            f.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            String appoin_id = jTextField16.getText();
            String doct_id = jTextField14.getText();
            String date = jTextField15.getText();
            String time = jTextField13.getText();

        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from appointment");
            ResultSet set = stmt.executeQuery();
            String appoi_id = jTextField16.getText();
            while (set.next()) {
                
                String id = set.getString("appointment_id");
                if (appoi_id.equals(id)) {
                    JOptionPane.showMessageDialog(this, "this ID is exist please choose another one", "Sorry", 2);
                    return;
                }
            }
        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }

        try {
            
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement s = c.prepareStatement("insert into appointment values(?,?,?,?)");
            // ResultSet stm=s.executeQuery();

            if ("".equals(appoin_id) || "".equals(doct_id) || "".equals(date) || "".equals(time)) {
                JOptionPane.showMessageDialog(null, "please fill all data carefully before press \"Add\"");

            } else {
                //s.setInt(1, Integer.parseInt(id));
                //for appointment_id
                s.setString(1, appoin_id);
                //ap.executeUpdate();
                //for doctor_id
                s.setString(2, doct_id);

                //for Data
                s.setString(3, date);

                //for Time
                s.setString(4, time);
                s.executeUpdate();

                JOptionPane.showMessageDialog(null, "Done...your data is added");

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "your \"Doctor_id\" may be wrong, please check it again before press \"Add\"");

            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel29KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel29KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29KeyPressed

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel30KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel30KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            DoctorPortal f = new DoctorPortal();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            DoctorLoginForm f = new DoctorLoginForm();
            this.setVisible(false);
            f.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        /*  else if(!check_id.equals("") && dt.equals("") && tm.equals(""))
        {
            JOptionPane.showMessageDialog(null,"this appointment ID doesn't exist ,please search for it again ");
            jTextField5.setText("");
            jTextField6.setText("");
           
        }
       else{  */
        try {
            String check_id = jTextField4.getText();
            String dt = jTextField5.getText();
            String tm = jTextField6.getText();
            if (check_id.equals("") || dt.equals("") || tm.equals("")) {
                JOptionPane.showMessageDialog(null, "please enter \"appointment ID\" and search for it before click \"update\" ");
                //return;
            } else {
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs?autoReconnect=true&useSSL=false", "root", "root");
                PreparedStatement stmt = con.prepareStatement("update appointment set Adate=?,Atime=? where appointment_id=?");

                stmt.setString(1, jTextField5.getText());
                stmt.setString(2, jTextField6.getText());
                stmt.setString(3, jTextField4.getText());
                stmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "Update Successfully....Done :D ");

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from appointment");
            ResultSet set = stmt.executeQuery();

            String check_id;
            check_id = jTextField4.getText();
            String dt = jTextField5.getText();
            String tm = jTextField6.getText();

            /* String id=(set.getString("appointment_id"));
            if(check_id.equals(id)){  
               //jTextField4.setText(set.getString("appointment_id"));
                 jTextField5.setText(set.getString("Adate"));
                 jTextField6.setText(set.getString("Atime"));
            //     break;  
            }  
           else if(check_id.equals("") && dt.equals("") &&  tm.equals("")){
             JOptionPane.showMessageDialog(null,"please enter the \"appointment ID\" to search for it");
             jTextField5.setText("");
             jTextField6.setText("");
                 
          //  break;
           }   
           if(!check_id.equals("appointment_id") && !check_id.equals("")){
                 JOptionPane.showMessageDialog(null,"this appointment ID doesn't exist ");
                 jTextField5.setText("");
                 jTextField6.setText("");
                // break;
                 
           } 
             */
            String id = "";
            while (set.next()) {

                id = (set.getString("appointment_id"));
                if (check_id.equals(id)) {
                    //          jTextField7.setText(set.getString("appointment_id"));
                    jTextField5.setText(set.getString("Adate"));
                    jTextField6.setText(set.getString("Atime"));
                    break;
                }

            }
            if (check_id.equals("")) {
                JOptionPane.showMessageDialog(null, "please enter the \"appointment ID\" to search for it");
                return;
            } else if (!check_id.equals(id)) {
                JOptionPane.showMessageDialog(null, "this \"appointment\" ID doesn't exist ");
                jTextField5.setText("");
                jTextField6.setText("");

            }

            if (jTextField4.getText().equals("")) {
                jTextField5.setText("");
                jTextField6.setText("");
            }

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel44KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel44KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel44KeyPressed

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel45MouseClicked

    private void jLabel45KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel45KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel45KeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            DoctorPortal f = new DoctorPortal();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            DoctorLoginForm f = new DoctorLoginForm();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jLabel59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel59MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel59MouseClicked

    private void jLabel59KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel59KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel59KeyPressed

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel60MouseClicked

    private void jLabel60KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel60KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel60KeyPressed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            DoctorPortal f = new DoctorPortal();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            DoctorLoginForm f = new DoctorLoginForm();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel62MouseClicked

    private void jLabel62KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel62KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel62KeyPressed

    private void jLabel63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel63MouseClicked

    private void jLabel63KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel63KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel63KeyPressed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            DoctorPortal f = new DoctorPortal();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            DoctorLoginForm f = new DoctorLoginForm();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        
                try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from appointment");
            ResultSet set = stmt.executeQuery();

            String check_id;
            check_id = jTextField7.getText();
           // String dt = jTextField5.getText();
           // String tm = jTextField6.getText();

            String id = "";
            while (set.next()) {

                id = (set.getString("appointment_id"));
                if (check_id.equals(id)) {
                    //          jTextField7.setText(set.getString("appointment_id"));
                    jTextField8.setText(set.getString("Adate"));
                    jTextField9.setText(set.getString("Atime"));
                    break;
                }

            }
            if (check_id.equals("")) {
                JOptionPane.showMessageDialog(null, "please enter the \"appointment ID\" to search for it");
                return;
            } else if (!check_id.equals(id)) {
                JOptionPane.showMessageDialog(null, "this \"appointment\" ID doesn't exist ");
                jTextField8.setText("");
                jTextField9.setText("");

            }

            if (jTextField7.getText().equals("")) {
                jTextField8.setText("");
                jTextField9.setText("");
            }

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }        
/*        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from appointment");
            ResultSet set = stmt.executeQuery();

            String check_id;
            check_id = jTextField7.getText();

            while (set.next()) {

                String id = (set.getString("appointment_id"));
                if (check_id.equals(id)) {
                    //          jTextField7.setText(set.getString("appointment_id"));
                    jTextField8.setText(set.getString("Adate"));
                    jTextField9.setText(set.getString("Atime"));
                    break;
                }
                if (check_id.equals("")) {
                    JOptionPane.showMessageDialog(null, "please enter the \"appointment ID\" to search for it");
                    break;
                } else if (!check_id.equals("appointment_id")) {
                    JOptionPane.showMessageDialog(null, "this appointment ID doesn't exist ");
                    jTextField8.setText("");
                    jTextField9.setText("");
                    break;
                }

            }

            if (jTextField7.getText().equals("")) {
                jTextField8.setText("");
                jTextField9.setText("");
            }
        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }*/

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        String check_id;
        check_id = jTextField7.getText();
        if ("".equals(jTextField7.getText()) || "".equals(jTextField8.getText()) || "".equals(jTextField9.getText())) {
            JOptionPane.showMessageDialog(this, "Please search about your \"appointment ID\" before press \"Delete\"", "Sorry", 2);
            return;
        }
                try {
            java.sql.Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt1 = con1.prepareStatement("select * from appointment");
            ResultSet set = stmt1.executeQuery();

            while (set.next()) {
                String id = set.getString("appointment_id");
                if (check_id.equals(id)) {
                    try {
                        java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs?autoReconnect=true&useSSL=false", "root", "root");
                        PreparedStatement stmt = con.prepareStatement("delete from appointment where appointment_id=?");
                        stmt.setInt(1, Integer.parseInt(check_id));
                        stmt.executeUpdate();
                        JOptionPane.showMessageDialog(null, "delete successfully", "done", JOptionPane.PLAIN_MESSAGE);
                        jTextField7.setText("");
                        jTextField8.setText("");
                        jTextField9.setText("");
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
                        System.out.println("Error" + ex.getErrorCode());
                    }
                    return;
                }

            }
            JOptionPane.showMessageDialog(this, "this ID isn't exist please choose another one", "Sorry", 2);
        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }



    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        
                       try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from appointment");
            ResultSet set = stmt.executeQuery();

            String check_id;
            check_id = jTextField12.getText();
           // String dt = jTextField11.getText();
           // String tm = jTextField10.getText();

            String id = "";
            while (set.next()) {

                id = (set.getString("appointment_id"));
                if (check_id.equals(id)) {
                    //          jTextField7.setText(set.getString("appointment_id"));
                    jTextField11.setText(set.getString("Adate"));
                    jTextField10.setText(set.getString("Atime"));
                    break;
                }

            }
            if (check_id.equals("")) {
                JOptionPane.showMessageDialog(null, "please enter the \"appointment ID\" to search for it");
                return;
            } else if (!check_id.equals(id)) {
                JOptionPane.showMessageDialog(null, "this \"appointment\" ID doesn't exist ");
                jTextField11.setText("");
                jTextField10.setText("");

            }

            if (jTextField12.getText().equals("")) {
                jTextField11.setText("");
                jTextField10.setText("");
            }

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }        

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs?autoReconnect=true&useSSL=false", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from appointment");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("Appointment ID");
            dm.addColumn("Date");
            dm.addColumn("Time");
            
            while (set.next()) {

                String r[] = {set.getString(1), set.getString(3),set.getString(4)};
                dm.addRow(r);
            }
            jTable1.setModel(dm);

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
