/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doctor;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author mahmoud160312
 */
public class Prescription extends javax.swing.JFrame {

    /**
     * Creates new form Prescription
     */
    public Prescription() {
        initComponents();
        CenteredFrame(this);
    }

    public void CenteredFrame(javax.swing.JFrame objFrame) {
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(0, 153, 204));
        jPanel6.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Prescription");
        jPanel6.add(jLabel1);
        jLabel1.setBounds(40, 0, 210, 70);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Logout");
        jLabel12.setToolTipText("");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jLabel12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel12KeyPressed(evt);
            }
        });
        jPanel6.add(jLabel12);
        jLabel12.setBounds(830, 50, 50, 20);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Home");
        jLabel15.setToolTipText("");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jLabel15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel15KeyPressed(evt);
            }
        });
        jPanel6.add(jLabel15);
        jLabel15.setBounds(780, 50, 50, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(790, 20, 30, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(840, 20, 30, 30);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(10, 50, 886, 70);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 204));
        jButton3.setText("Add");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(697, 164, 153, 42);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(180, 310, 190, 30);

        jLabel11.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 204));
        jLabel11.setText(" date:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 430, 110, 30);

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(180, 270, 190, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 204));
        jLabel13.setText("Patient ID:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 270, 110, 30);

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(180, 350, 190, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 204));
        jLabel14.setText("Patient Name:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(60, 310, 110, 30);

        jLabel16.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 204));
        jLabel16.setText("Doctor ID:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(60, 350, 110, 30);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(180, 390, 190, 30);

        jLabel17.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 204));
        jLabel17.setText("Doctor Name:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(60, 390, 110, 30);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(180, 430, 190, 30);

        jLabel21.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 204));
        jLabel21.setText("Description");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(430, 230, 160, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(590, 230, 270, 150);

        jLabel18.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 204));
        jLabel18.setText("Prescription ID:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(60, 230, 120, 30);

        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(180, 230, 190, 30);

        jTabbedPane1.addTab("Add Prescription", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select *from doctor");

            ResultSet set = stmt.executeQuery();

            String check_id;
            check_id = jTextField4.getText();

            String id = "", first_name = "", second_name = "";

            while (set.next()) {
                id = set.getString("doctor_id");

                if (check_id.equals(id)) {
                    first_name = set.getString("first_name");
                    second_name = set.getString("second_name");
                    break;
                }

            }
            //check if it empty********************************
            if ("".equals(check_id)) {
                JOptionPane.showMessageDialog(this, "please write doctor ID first before click search", "ALARM", JOptionPane.ERROR_MESSAGE);
            } //************** check for exist*********************************
            else if (!check_id.equals(id)) {
                JOptionPane.showMessageDialog(this, "The Doctor isn't Exist", "Sorry", JOptionPane.INFORMATION_MESSAGE);
                jTextField4.setText("");
                jTextField6.setText("");

            } else {
                jTextField6.setText(first_name + " " + second_name);

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost

        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select *from patient");

            ResultSet set = stmt.executeQuery();

            String check_id;
            check_id = jTextField3.getText();

            String id = "", first_name = "", second_name = "";

            while (set.next()) {
                id = set.getString("patient_id");

                if (check_id.equals(id)) {
                    first_name = set.getString("first_name");
                    second_name = set.getString("second_name");
                    break;
                }

            }
            //check if it empty********************************
            if ("".equals(check_id)) {
                JOptionPane.showMessageDialog(this, "please write Patient ID first before click search", "ALARM", JOptionPane.ERROR_MESSAGE);
            } //************** check for exist*********************************
            else if (!check_id.equals(id)) {
                JOptionPane.showMessageDialog(this, "The Patient isn't Exist", "Sorry", JOptionPane.INFORMATION_MESSAGE);
                jTextField3.setText("");
                jTextField1.setText("");

            } else {
                jTextField1.setText(first_name + " " + second_name);

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jTextField3FocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from give");
            PreparedStatement stmt2 = con.prepareStatement("select * from patient ");
            PreparedStatement stmt3 = con.prepareStatement("select * from doctor ");
            PreparedStatement stmt4 = con.prepareStatement("select * from prescription ");
            String checkPrescription_id = jTextField5.getText();
            String checkPatient_id = jTextField3.getText();
            String checkDoctor_id = jTextField4.getText();
            String cDate = jTextField7.getText();
            String cDescription = jTextArea1.getText();
            String patient_id, doctor_id = "", prescription_id = "";
            ResultSet set = stmt.executeQuery();
            while (set.next()) {
                patient_id = set.getString("patient_id");
                doctor_id = set.getString("doctor_id");
                prescription_id = set.getString("prescription_id");
                break;
            }
            if ("".equals(checkPrescription_id) || "".equals(checkPatient_id) || "".equals(checkDoctor_id) || "".equals(cDate) || "".equals(cDescription)) {
                JOptionPane.showMessageDialog(this, "please Fill all the data first before click \"Search\"", "ALARM", JOptionPane.ERROR_MESSAGE);
            } else if (checkPrescription_id.equals(prescription_id)) {
                JOptionPane.showMessageDialog(this, " this Prescription's ID is Exist, please choose another one", "Sorry", JOptionPane.INFORMATION_MESSAGE);
                jTextField1.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextArea1.setText("");

            } else {
                try {
                    Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
                    PreparedStatement s = c.prepareStatement("insert into give values(?,?,?)");
                    PreparedStatement s2 = c.prepareStatement("insert into prescription values(?,?,?)");
                    s.setInt(1, Integer.parseInt(checkPatient_id));
                    s.setInt(3, Integer.parseInt(checkDoctor_id));
                    s.setInt(2, Integer.parseInt(checkPrescription_id));
                    s2.setInt(1, Integer.parseInt(checkPrescription_id));
                    s2.setString(2, cDescription);
                    s2.setString(3, cDate);
                    s2.executeUpdate();
                    s.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Added successfully :D", "done!", JOptionPane.PLAIN_MESSAGE);
                    jTextField5.setText("");
                    jTextField1.setText("");
                    jTextField6.setText("");

                    jTextField4.setText("");
                    jTextField3.setText("");

                    jTextField7.setText("");
                    jTextArea1.setText("");

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
                    System.out.println("Error" + ex.getErrorCode());
                }

            }

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            DoctorLoginForm f = new DoctorLoginForm();
            this.setVisible(false);
            f.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            DoctorPortal f = new DoctorPortal();
            this.setVisible(false);
            f.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jLabel15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel15KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15KeyPressed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel12KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12KeyPressed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
