/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import admin.AdminPortal;
import admin.AdminLoginForm;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mahmoud160312
 */
public class ChangeAdminUsernameAndPassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangeAdminUsernameAndPassword
     */
    public ChangeAdminUsernameAndPassword() {
        initComponents();
        jLabel3.setVisible(false);
        jLabel2.setVisible(false);
        CenteredFrame(this);
    }

    public void CenteredFrame(javax.swing.JFrame objFrame) {
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Change = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newAdminUserName = new javax.swing.JTextField();
        newAdminPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<<");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jLabel7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel7KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 10, 24, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        Change.setBackground(new java.awt.Color(0, 153, 204));
        Change.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Change.setForeground(new java.awt.Color(255, 255, 255));
        Change.setText("Change");
        Change.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeActionPerformed(evt);
            }
        });
        jPanel2.add(Change);
        Change.setBounds(110, 180, 127, 39);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("New Password");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 92, 122, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("New Username");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 43, 115, 30);

        newAdminUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAdminUserNameActionPerformed(evt);
            }
        });
        newAdminUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newAdminUserNameKeyTyped(evt);
            }
        });
        jPanel2.add(newAdminUserName);
        newAdminUserName.setBounds(150, 44, 180, 30);

        newAdminPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newAdminPasswordKeyTyped(evt);
            }
        });
        jPanel2.add(newAdminPassword);
        newAdminPassword.setBounds(150, 93, 180, 30);

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("password must have a value");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(160, 120, 160, 20);

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("username must have a value");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 70, 160, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 170, 360, 290);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/change the password photo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 360, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeActionPerformed
        {
            if ("".equals(newAdminUserName.getText()) || "".equals(newAdminPassword.getText())) {
                if ("".equals(newAdminUserName.getText())) {
                    jLabel3.setVisible(true);
                }

                if ((!"".equals(newAdminUserName.getText()))) {
                    jLabel3.setVisible(false);
                }
                if ("".equals(newAdminPassword.getText())) {
                    jLabel2.setVisible(true);
                }

                if (!"".equals(newAdminPassword.getText())) {
                    jLabel2.setVisible(false);
                }
            } else {
                PrintWriter writer = null;
                try {
                    writer = new PrintWriter("adminLogin.qvm", "UTF-8");
                } catch (FileNotFoundException | UnsupportedEncodingException ex) {
                    Logger.getLogger(AdminLoginForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                writer.println(newAdminUserName.getText());
                writer.println(newAdminPassword.getText());
                writer.close();
                int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to change the Username and the Password", "", JOptionPane.YES_NO_OPTION, 1);
                if (replay == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(this, "the Username and the password are setted successfully", "done!", JOptionPane.PLAIN_MESSAGE);
                    AdminPortal f = new AdminPortal();
                    this.setVisible(false);
                    f.setVisible(true);
                }

            }


    }//GEN-LAST:event_ChangeActionPerformed
    }
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        AdminPortal f = new AdminPortal();
        this.setVisible(false);
        f.setVisible(true);

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel7KeyPressed
        AdminPortal f = new AdminPortal();
        this.setVisible(false);
        f.setVisible(true);
    }//GEN-LAST:event_jLabel7KeyPressed

    private void newAdminUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAdminUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newAdminUserNameActionPerformed

    private void newAdminUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newAdminUserNameKeyTyped
        jLabel3.setVisible(false);
    }//GEN-LAST:event_newAdminUserNameKeyTyped

    private void newAdminPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newAdminPasswordKeyTyped
        jLabel2.setVisible(false);
    }//GEN-LAST:event_newAdminPasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeAdminUsernameAndPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeAdminUsernameAndPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeAdminUsernameAndPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeAdminUsernameAndPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeAdminUsernameAndPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Change;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField newAdminPassword;
    private javax.swing.JTextField newAdminUserName;
    // End of variables declaration//GEN-END:variables
}
