/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahmoud160312
 */
public class NurseDetails extends javax.swing.JFrame {

    /**
     * Creates new form PatientDetails
     */
    public NurseDetails() {
        initComponents();
        CenteredFrame(this);
    }

    public void CenteredFrame(javax.swing.JFrame objFrame) {
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel103 = new javax.swing.JLabel();
        jTextField72 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jComboBox11 = new javax.swing.JComboBox<>();
        jTextField73 = new javax.swing.JTextField();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jLabel106 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton16 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel107 = new javax.swing.JLabel();
        jTextField75 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jComboBox12 = new javax.swing.JComboBox<>();
        jTextField77 = new javax.swing.JTextField();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        jLabel111 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton15 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel112 = new javax.swing.JLabel();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jComboBox13 = new javax.swing.JComboBox<>();
        jTextField81 = new javax.swing.JTextField();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jTextField82 = new javax.swing.JTextField();
        jLabel117 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel118 = new javax.swing.JLabel();
        jTextField69 = new javax.swing.JTextField();
        jTextField83 = new javax.swing.JTextField();
        jComboBox14 = new javax.swing.JComboBox<>();
        jTextField51 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(0, 153, 204));
        jPanel6.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Nurse");
        jPanel6.add(jLabel1);
        jLabel1.setBounds(0, 0, 210, 70);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Logout");
        jLabel12.setToolTipText("");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jLabel12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel12KeyPressed(evt);
            }
        });
        jPanel6.add(jLabel12);
        jLabel12.setBounds(830, 50, 50, 20);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Home");
        jLabel15.setToolTipText("");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jLabel15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel15KeyPressed(evt);
            }
        });
        jPanel6.add(jLabel15);
        jLabel15.setBounds(780, 50, 50, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(790, 20, 30, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(840, 20, 30, 30);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(10, 50, 886, 70);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 204));
        jButton3.setText("Add");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(727, 164, 153, 42);

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("City:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 459, 110, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("Status:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 340, 110, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("Phone: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 459, 60, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 204));
        jLabel8.setText("Salary");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 518, 89, 30);

        jLabel11.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 204));
        jLabel11.setText("Address:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 399, 110, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 204));
        jLabel13.setText("Nurse ID:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(80, 170, 69, 30);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(170, 400, 470, 30);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(170, 459, 140, 30);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(170, 519, 140, 30);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(496, 460, 150, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(170, 170, 140, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 153, 204));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Married ", "Single" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(170, 340, 140, 30);

        jLabel20.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 204));
        jLabel20.setText("Ward NO");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(70, 570, 80, 30);
        jPanel1.add(jTextField14);
        jTextField14.setBounds(170, 570, 150, 30);

        jLabel103.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(0, 153, 204));
        jLabel103.setText("Specialist:");
        jPanel1.add(jLabel103);
        jLabel103.setBounds(360, 520, 90, 30);

        jTextField72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField72ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField72);
        jTextField72.setBounds(500, 520, 150, 30);
        jPanel1.add(jTextField68);
        jTextField68.setBounds(500, 330, 150, 30);

        jComboBox11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox11.setForeground(new java.awt.Color(0, 153, 204));
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Male", "Female" }));
        jPanel1.add(jComboBox11);
        jComboBox11.setBounds(500, 280, 150, 30);
        jPanel1.add(jTextField73);
        jTextField73.setBounds(500, 230, 150, 30);

        jLabel101.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(0, 153, 204));
        jLabel101.setText("Second Name:");
        jPanel1.add(jLabel101);
        jLabel101.setBounds(364, 226, 110, 30);

        jLabel102.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(0, 153, 204));
        jLabel102.setText("Gender:");
        jPanel1.add(jLabel102);
        jLabel102.setBounds(370, 280, 80, 30);

        jLabel104.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(0, 153, 204));
        jLabel104.setText("Date:");
        jPanel1.add(jLabel104);
        jLabel104.setBounds(370, 330, 110, 30);

        jLabel105.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(0, 153, 204));
        jLabel105.setText("Age:");
        jPanel1.add(jLabel105);
        jLabel105.setBounds(80, 276, 80, 30);
        jPanel1.add(jTextField22);
        jTextField22.setBounds(170, 276, 140, 30);
        jPanel1.add(jTextField74);
        jTextField74.setBounds(170, 227, 140, 30);

        jLabel106.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(0, 153, 204));
        jLabel106.setText("First Name:");
        jPanel1.add(jLabel106);
        jLabel106.setBounds(80, 226, 90, 30);

        jTabbedPane2.addTab("Add Nurse", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(0, 153, 204));
        jPanel7.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Update Nurse");
        jPanel7.add(jLabel28);
        jLabel28.setBounds(0, 0, 250, 70);

        jLabel29.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Logout");
        jLabel29.setToolTipText("");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jLabel29.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel29KeyPressed(evt);
            }
        });
        jPanel7.add(jLabel29);
        jLabel29.setBounds(830, 50, 50, 20);

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Home");
        jLabel30.setToolTipText("");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jLabel30.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel30KeyPressed(evt);
            }
        });
        jPanel7.add(jLabel30);
        jLabel30.setBounds(780, 50, 50, 20);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4);
        jButton4.setBounds(790, 20, 30, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5);
        jButton5.setBounds(840, 20, 30, 30);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(10, 50, 886, 70);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 153, 204));
        jButton6.setText("Update");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(720, 160, 153, 42);

        jLabel27.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 153, 204));
        jLabel27.setText("City:");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(80, 459, 110, 30);

        jLabel42.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 153, 204));
        jLabel42.setText("Status:");
        jPanel2.add(jLabel42);
        jLabel42.setBounds(80, 340, 110, 30);

        jLabel57.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 153, 204));
        jLabel57.setText("Phone: ");
        jPanel2.add(jLabel57);
        jLabel57.setBounds(360, 459, 60, 30);

        jLabel66.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 153, 204));
        jLabel66.setText("Salary");
        jPanel2.add(jLabel66);
        jLabel66.setBounds(80, 518, 89, 30);

        jLabel69.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 153, 204));
        jLabel69.setText("Address:");
        jPanel2.add(jLabel69);
        jLabel69.setBounds(80, 399, 110, 30);

        jLabel70.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 153, 204));
        jLabel70.setText("Nurse ID:");
        jPanel2.add(jLabel70);
        jLabel70.setBounds(80, 170, 69, 30);
        jPanel2.add(jTextField29);
        jTextField29.setBounds(170, 400, 470, 30);
        jPanel2.add(jTextField39);
        jTextField39.setBounds(170, 459, 140, 30);
        jPanel2.add(jTextField41);
        jTextField41.setBounds(170, 519, 140, 30);
        jPanel2.add(jTextField44);
        jTextField44.setBounds(496, 460, 150, 30);
        jPanel2.add(jTextField45);
        jTextField45.setBounds(170, 170, 140, 30);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(0, 153, 204));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Married ", "Single" }));
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(170, 340, 140, 30);

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 153, 204));
        jButton16.setText("Search");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16);
        jButton16.setBounds(370, 160, 153, 42);

        jLabel21.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 204));
        jLabel21.setText("Ward NO");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(70, 570, 80, 30);
        jPanel2.add(jTextField15);
        jTextField15.setBounds(170, 570, 150, 30);

        jLabel107.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(0, 153, 204));
        jLabel107.setText("Specialist:");
        jPanel2.add(jLabel107);
        jLabel107.setBounds(360, 520, 90, 30);

        jTextField75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField75ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField75);
        jTextField75.setBounds(500, 520, 150, 30);
        jPanel2.add(jTextField76);
        jTextField76.setBounds(500, 330, 150, 30);

        jComboBox12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox12.setForeground(new java.awt.Color(0, 153, 204));
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Male", "Female" }));
        jPanel2.add(jComboBox12);
        jComboBox12.setBounds(500, 280, 150, 30);
        jPanel2.add(jTextField77);
        jTextField77.setBounds(500, 230, 150, 30);

        jLabel108.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(0, 153, 204));
        jLabel108.setText("Second Name:");
        jPanel2.add(jLabel108);
        jLabel108.setBounds(364, 226, 110, 30);

        jLabel109.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(0, 153, 204));
        jLabel109.setText("Gender:");
        jPanel2.add(jLabel109);
        jLabel109.setBounds(370, 280, 80, 30);

        jLabel110.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(0, 153, 204));
        jLabel110.setText("Date:");
        jPanel2.add(jLabel110);
        jLabel110.setBounds(370, 330, 110, 30);

        jLabel100.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(0, 153, 204));
        jLabel100.setText("Age:");
        jPanel2.add(jLabel100);
        jLabel100.setBounds(80, 276, 80, 30);
        jPanel2.add(jTextField23);
        jTextField23.setBounds(170, 276, 140, 30);
        jPanel2.add(jTextField78);
        jTextField78.setBounds(170, 227, 140, 30);

        jLabel111.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(0, 153, 204));
        jLabel111.setText("First Name:");
        jPanel2.add(jLabel111);
        jLabel111.setBounds(80, 226, 90, 30);

        jTabbedPane2.addTab("Update  Nurse", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(0, 153, 204));
        jPanel8.setLayout(null);

        jLabel43.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Delete Nurse");
        jPanel8.add(jLabel43);
        jLabel43.setBounds(0, 0, 250, 70);

        jLabel44.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Logout");
        jLabel44.setToolTipText("");
        jLabel44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        jLabel44.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel44KeyPressed(evt);
            }
        });
        jPanel8.add(jLabel44);
        jLabel44.setBounds(830, 50, 50, 20);

        jLabel45.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Home");
        jLabel45.setToolTipText("");
        jLabel45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        jLabel45.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel45KeyPressed(evt);
            }
        });
        jPanel8.add(jLabel45);
        jLabel45.setBounds(780, 50, 50, 20);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton7);
        jButton7.setBounds(790, 20, 30, 30);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton8);
        jButton8.setBounds(840, 20, 30, 30);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(10, 50, 886, 70);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 153, 204));
        jButton9.setText("Delete");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);
        jButton9.setBounds(720, 160, 153, 42);

        jLabel83.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(0, 153, 204));
        jLabel83.setText("City:");
        jPanel3.add(jLabel83);
        jLabel83.setBounds(80, 459, 110, 30);

        jLabel84.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(0, 153, 204));
        jLabel84.setText("Status:");
        jPanel3.add(jLabel84);
        jLabel84.setBounds(80, 340, 110, 30);

        jLabel85.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(0, 153, 204));
        jLabel85.setText("Phone: ");
        jPanel3.add(jLabel85);
        jLabel85.setBounds(360, 459, 60, 30);

        jLabel88.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(0, 153, 204));
        jLabel88.setText("Salary");
        jPanel3.add(jLabel88);
        jLabel88.setBounds(80, 518, 89, 30);

        jLabel91.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(0, 153, 204));
        jLabel91.setText("Address:");
        jPanel3.add(jLabel91);
        jLabel91.setBounds(80, 399, 110, 30);

        jLabel92.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(0, 153, 204));
        jLabel92.setText("Nurse ID:");
        jPanel3.add(jLabel92);
        jLabel92.setBounds(80, 170, 69, 30);

        jTextField57.setForeground(new java.awt.Color(0, 0, 255));
        jTextField57.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField57.setEnabled(false);
        jPanel3.add(jTextField57);
        jTextField57.setBounds(170, 400, 470, 30);

        jTextField58.setForeground(new java.awt.Color(0, 0, 255));
        jTextField58.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField58.setEnabled(false);
        jPanel3.add(jTextField58);
        jTextField58.setBounds(170, 459, 140, 30);

        jTextField59.setForeground(new java.awt.Color(0, 0, 255));
        jTextField59.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField59.setEnabled(false);
        jPanel3.add(jTextField59);
        jTextField59.setBounds(170, 519, 140, 30);

        jTextField62.setForeground(new java.awt.Color(0, 0, 255));
        jTextField62.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField62.setEnabled(false);
        jPanel3.add(jTextField62);
        jTextField62.setBounds(496, 460, 150, 30);
        jPanel3.add(jTextField63);
        jTextField63.setBounds(170, 170, 140, 30);

        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(0, 0, 255));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Married ", "Single" }));
        jPanel3.add(jComboBox5);
        jComboBox5.setBounds(170, 340, 140, 30);

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(0, 153, 204));
        jButton15.setText("Search");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton15);
        jButton15.setBounds(370, 160, 153, 42);

        jLabel22.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 204));
        jLabel22.setText("Ward NO");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(70, 570, 80, 30);

        jTextField16.setForeground(new java.awt.Color(0, 0, 255));
        jTextField16.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField16.setEnabled(false);
        jPanel3.add(jTextField16);
        jTextField16.setBounds(170, 570, 150, 30);

        jLabel112.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(0, 153, 204));
        jLabel112.setText("Specialist:");
        jPanel3.add(jLabel112);
        jLabel112.setBounds(360, 520, 90, 30);

        jTextField79.setForeground(new java.awt.Color(0, 0, 255));
        jTextField79.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField79.setEnabled(false);
        jTextField79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField79ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField79);
        jTextField79.setBounds(500, 520, 150, 30);

        jTextField80.setForeground(new java.awt.Color(0, 0, 255));
        jTextField80.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField80.setEnabled(false);
        jPanel3.add(jTextField80);
        jTextField80.setBounds(500, 330, 150, 30);

        jComboBox13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox13.setForeground(new java.awt.Color(0, 0, 255));
        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Male", "Female" }));
        jPanel3.add(jComboBox13);
        jComboBox13.setBounds(500, 280, 150, 30);

        jTextField81.setForeground(new java.awt.Color(0, 0, 255));
        jTextField81.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField81.setEnabled(false);
        jPanel3.add(jTextField81);
        jTextField81.setBounds(500, 230, 150, 30);

        jLabel113.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(0, 153, 204));
        jLabel113.setText("Second Name:");
        jPanel3.add(jLabel113);
        jLabel113.setBounds(364, 226, 110, 30);

        jLabel114.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(0, 153, 204));
        jLabel114.setText("Gender:");
        jPanel3.add(jLabel114);
        jLabel114.setBounds(370, 280, 80, 30);

        jLabel115.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(0, 153, 204));
        jLabel115.setText("Date:");
        jPanel3.add(jLabel115);
        jLabel115.setBounds(370, 330, 110, 30);

        jLabel116.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(0, 153, 204));
        jLabel116.setText("Age:");
        jPanel3.add(jLabel116);
        jLabel116.setBounds(80, 276, 80, 30);

        jTextField24.setForeground(new java.awt.Color(0, 0, 255));
        jTextField24.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField24.setEnabled(false);
        jPanel3.add(jTextField24);
        jTextField24.setBounds(170, 276, 140, 30);

        jTextField82.setForeground(new java.awt.Color(0, 0, 255));
        jTextField82.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField82.setEnabled(false);
        jPanel3.add(jTextField82);
        jTextField82.setBounds(170, 227, 140, 30);

        jLabel117.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel117.setForeground(new java.awt.Color(0, 153, 204));
        jLabel117.setText("First Name:");
        jPanel3.add(jLabel117);
        jLabel117.setBounds(80, 226, 90, 30);

        jTabbedPane2.addTab("Delete Nurse", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(0, 153, 204));
        jPanel9.setLayout(null);

        jLabel58.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("   Search Nurse");
        jPanel9.add(jLabel58);
        jLabel58.setBounds(0, 0, 230, 70);

        jLabel59.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Logout");
        jLabel59.setToolTipText("");
        jLabel59.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel59MouseClicked(evt);
            }
        });
        jLabel59.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel59KeyPressed(evt);
            }
        });
        jPanel9.add(jLabel59);
        jLabel59.setBounds(830, 50, 50, 20);

        jLabel60.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("Home");
        jLabel60.setToolTipText("");
        jLabel60.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });
        jLabel60.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel60KeyPressed(evt);
            }
        });
        jPanel9.add(jLabel60);
        jLabel60.setBounds(780, 50, 50, 20);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton10);
        jButton10.setBounds(790, 20, 30, 30);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton11);
        jButton11.setBounds(840, 20, 30, 30);

        jPanel4.add(jPanel9);
        jPanel9.setBounds(10, 50, 886, 70);

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 153, 204));
        jButton12.setText("Search");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);
        jButton12.setBounds(370, 160, 153, 42);

        jLabel72.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 153, 204));
        jLabel72.setText("City:");
        jPanel4.add(jLabel72);
        jLabel72.setBounds(80, 459, 110, 30);

        jLabel73.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(0, 153, 204));
        jLabel73.setText("Status:");
        jPanel4.add(jLabel73);
        jLabel73.setBounds(80, 340, 110, 30);

        jLabel74.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(0, 153, 204));
        jLabel74.setText("Phone: ");
        jPanel4.add(jLabel74);
        jLabel74.setBounds(360, 459, 60, 30);

        jLabel77.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(0, 153, 204));
        jLabel77.setText("Salary");
        jPanel4.add(jLabel77);
        jLabel77.setBounds(80, 518, 89, 30);

        jLabel80.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(0, 153, 204));
        jLabel80.setText("Address:");
        jPanel4.add(jLabel80);
        jLabel80.setBounds(80, 399, 110, 30);

        jLabel81.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(0, 153, 204));
        jLabel81.setText("Nurse ID:");
        jPanel4.add(jLabel81);
        jLabel81.setBounds(80, 170, 69, 30);

        jTextField48.setForeground(new java.awt.Color(0, 51, 204));
        jTextField48.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField48.setEnabled(false);
        jPanel4.add(jTextField48);
        jTextField48.setBounds(170, 400, 470, 30);

        jTextField49.setForeground(new java.awt.Color(0, 51, 204));
        jTextField49.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField49.setEnabled(false);
        jPanel4.add(jTextField49);
        jTextField49.setBounds(170, 459, 140, 30);

        jTextField50.setForeground(new java.awt.Color(0, 51, 204));
        jTextField50.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField50.setEnabled(false);
        jPanel4.add(jTextField50);
        jTextField50.setBounds(170, 519, 140, 30);

        jTextField53.setForeground(new java.awt.Color(0, 51, 204));
        jTextField53.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField53.setEnabled(false);
        jPanel4.add(jTextField53);
        jTextField53.setBounds(496, 460, 150, 30);
        jPanel4.add(jTextField54);
        jTextField54.setBounds(170, 170, 140, 30);

        jComboBox7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox7.setForeground(new java.awt.Color(0, 0, 255));
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Married ", "Single" }));
        jPanel4.add(jComboBox7);
        jComboBox7.setBounds(170, 340, 140, 30);

        jLabel23.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 204));
        jLabel23.setText("Ward NO");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(70, 570, 80, 30);

        jTextField17.setForeground(new java.awt.Color(0, 51, 204));
        jTextField17.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField17.setEnabled(false);
        jPanel4.add(jTextField17);
        jTextField17.setBounds(170, 570, 150, 30);

        jLabel118.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(0, 153, 204));
        jLabel118.setText("Specialist:");
        jPanel4.add(jLabel118);
        jLabel118.setBounds(360, 520, 90, 30);

        jTextField69.setForeground(new java.awt.Color(0, 51, 204));
        jTextField69.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField69.setEnabled(false);
        jTextField69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField69ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField69);
        jTextField69.setBounds(500, 520, 150, 30);

        jTextField83.setForeground(new java.awt.Color(0, 51, 204));
        jTextField83.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField83.setEnabled(false);
        jPanel4.add(jTextField83);
        jTextField83.setBounds(500, 330, 150, 30);

        jComboBox14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox14.setForeground(new java.awt.Color(0, 0, 255));
        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Male", "Female" }));
        jPanel4.add(jComboBox14);
        jComboBox14.setBounds(500, 280, 150, 30);

        jTextField51.setForeground(new java.awt.Color(0, 51, 204));
        jTextField51.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField51.setEnabled(false);
        jPanel4.add(jTextField51);
        jTextField51.setBounds(500, 230, 150, 30);

        jLabel79.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(0, 153, 204));
        jLabel79.setText("Second Name:");
        jPanel4.add(jLabel79);
        jLabel79.setBounds(364, 226, 110, 30);

        jLabel119.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel119.setForeground(new java.awt.Color(0, 153, 204));
        jLabel119.setText("Gender:");
        jPanel4.add(jLabel119);
        jLabel119.setBounds(370, 280, 80, 30);

        jLabel120.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel120.setForeground(new java.awt.Color(0, 153, 204));
        jLabel120.setText("Date:");
        jPanel4.add(jLabel120);
        jLabel120.setBounds(370, 330, 110, 30);

        jLabel121.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel121.setForeground(new java.awt.Color(0, 153, 204));
        jLabel121.setText("Age:");
        jPanel4.add(jLabel121);
        jLabel121.setBounds(80, 276, 80, 30);

        jTextField25.setForeground(new java.awt.Color(0, 51, 204));
        jTextField25.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField25.setEnabled(false);
        jPanel4.add(jTextField25);
        jTextField25.setBounds(170, 276, 140, 30);

        jTextField46.setForeground(new java.awt.Color(0, 51, 204));
        jTextField46.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        jTextField46.setEnabled(false);
        jPanel4.add(jTextField46);
        jTextField46.setBounds(170, 227, 140, 30);

        jLabel71.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 153, 204));
        jLabel71.setText("First Name:");
        jPanel4.add(jLabel71);
        jLabel71.setBounds(80, 226, 90, 30);

        jTabbedPane2.addTab("   Search Nurse", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jButton17.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 153, 204));
        jButton17.setText("Show");
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton17);
        jButton17.setBounds(770, 560, 153, 42);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nurse ID:", "First Name", "Second Name", "Address", "Age", "Status", "Gender", "Phone", "City", "Salary", "specialist", "Date", "Ward Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Long.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(10).setPreferredWidth(110);
        }

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(0, 170, 930, 460);

        jPanel10.setBackground(new java.awt.Color(0, 153, 204));
        jPanel10.setLayout(null);

        jLabel61.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("View Nurse");
        jPanel10.add(jLabel61);
        jLabel61.setBounds(0, 0, 220, 70);

        jLabel62.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("Logout");
        jLabel62.setToolTipText("");
        jLabel62.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        jLabel62.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel62KeyPressed(evt);
            }
        });
        jPanel10.add(jLabel62);
        jLabel62.setBounds(830, 50, 50, 20);

        jLabel63.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Home");
        jLabel63.setToolTipText("");
        jLabel63.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel63MouseClicked(evt);
            }
        });
        jLabel63.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel63KeyPressed(evt);
            }
        });
        jPanel10.add(jLabel63);
        jLabel63.setBounds(780, 50, 50, 20);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton13);
        jButton13.setBounds(790, 20, 30, 30);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton14);
        jButton14.setBounds(840, 20, 30, 30);

        jPanel5.add(jPanel10);
        jPanel10.setBounds(10, 50, 910, 70);

        jTabbedPane2.addTab("View Nurse", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel12KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12KeyPressed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel15KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            AdminPortal f = new AdminPortal();
            this.setVisible(false);
            f.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String id = jTextField3.getText();
        String firstName = jTextField74.getText();
        String secondName = jTextField73.getText();
        String age = jTextField22.getText();
        String address = jTextField4.getText();
        String gender = jComboBox11.getSelectedItem().toString();
        String status = jComboBox2.getSelectedItem().toString();
        String phone = jTextField10.getText();
        String city = jTextField5.getText();
        String date = jTextField68.getText();
        String salary = jTextField6.getText();
        String specialist = jTextField72.getText();
        String wardNo = jTextField14.getText();
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from nurse");
            ResultSet set = stmt.executeQuery();
            String check_id, cWardNo;
            check_id = jTextField3.getText();
            cWardNo = jTextField14.getText();
            while (set.next()) {
                id = set.getString("nurse_id");
                wardNo = set.getString("Ward_id");
                if (check_id.equals(id)) {
                    JOptionPane.showMessageDialog(this, "this ID is exist please choose another one", "Sorry", 2);
                    return;
                }
                if (cWardNo.equals(wardNo)) {
                    JOptionPane.showMessageDialog(this, "this ward already have a nurse choose another ward", "Sorry", 2);
                    return;
                }
                
                if (Integer.parseInt(cWardNo)>5) {
                    JOptionPane.showMessageDialog(this, "Sorry but there is only five wards ", "Sorry", 2);
                    return;
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement s = c.prepareStatement("insert into nurse values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
            if ("".equals(id) || "".equals(firstName) || "".equals(age) || "".equals(address) || "select".equals(gender) || "".equals(phone) || "".equals(city) || "select".equals(status) || "".equals(date) || "".equals(secondName) || "".equals(specialist) || "".equals(salary)) {
                JOptionPane.showMessageDialog(this, "Please Fill all Data carefully before press \"ADD\"", "Sorry", 2);
            } else {
                s.setInt(1, Integer.parseInt(jTextField3.getText()));
                s.setString(2, firstName);
                s.setString(3, secondName);
                s.setInt(5, Integer.parseInt(age));
                s.setString(4, address);
                s.setString(7, gender);
                s.setInt(8, Integer.parseInt(phone));
                s.setString(9, city);
                s.setString(6, status);
                s.setString(12, date);
                s.setDouble(10, Double.parseDouble(salary));
                s.setString(11, specialist);
                s.setInt(13, Integer.parseInt(jTextField14.getText()));
                s.executeUpdate();
                JOptionPane.showMessageDialog(null, "Added successfully :D", "done!", JOptionPane.PLAIN_MESSAGE);
                jTextField74.setText("");
                jTextField73.setText("");
                jTextField22.setText("");
                jTextField4.setText("");
                jComboBox11.setSelectedItem(0);
                jComboBox2.setSelectedItem(0);
                jTextField10.setText("");
                jTextField5.setText("");
                jTextField68.setText("");
                jTextField6.setText("");
                jTextField72.setText("");
                jTextField14.setText("");

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            AdminLoginForm f = new AdminLoginForm();
            this.setVisible(false);
            f.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel29KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel29KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29KeyPressed

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel30KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel30KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            AdminPortal f = new AdminPortal();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            AdminLoginForm f = new AdminLoginForm();
            this.setVisible(false);
            f.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String firstName = jTextField78.getText();
        String secondName = jTextField77.getText();
        String age = jTextField23.getText();
        String address = jTextField29.getText();
        String phone = jTextField44.getText();
        String city = jTextField39.getText();
        String date = jTextField76.getText();
        String salary = jTextField41.getText();
        String specialist = jTextField75.getText();
        String wardNo = jTextField15.getText();
        String check_id;
        check_id = jTextField45.getText();
        String gender = jComboBox12.getSelectedItem().toString();
        String status = jComboBox3.getSelectedItem().toString();
        if ("".equals(jTextField45.getText()) || "".equals(jTextField76.getText()) || "".equals(jTextField41.getText())) {
            JOptionPane.showMessageDialog(this, "Please search about your Nurse before press \"Update\"", "Sorry", 2);
            return;
        }
        try {
            java.sql.Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt1 = con1.prepareStatement("select * from nurse");
            ResultSet set = stmt1.executeQuery();
            while (set.next()) {
                String id = set.getString("nurse_id");

                if (check_id.equals(id)) {
                    try {
                        java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
                        PreparedStatement stmt = con.prepareStatement("update nurse set first_name=?,second_name=?"
                                + ",age=?,address=?,gender=?,phone=?,city=?,Nstatus=?,Ndate=?,salary=?,specialist=?,ward_id=? where nurse_id=?");

                        stmt.setString(1, firstName);
                        stmt.setString(2, secondName);
                        stmt.setInt(3, Integer.parseInt(age));
                        stmt.setString(4, address);
                        stmt.setString(5, gender);
                        stmt.setInt(6, Integer.parseInt(phone));
                        stmt.setString(7, city);
                        stmt.setString(8, status);
                        stmt.setString(9, date);
                        stmt.setDouble(10, Double.parseDouble(salary));
                        stmt.setString(11, specialist);
                        stmt.setInt(12, Integer.parseInt(wardNo));
                        stmt.setInt(13, Integer.parseInt(check_id));
                        stmt.executeUpdate();
                        JOptionPane.showMessageDialog(null, "update successfully", "done", JOptionPane.PLAIN_MESSAGE);
                    } catch (SQLException ex) {
                        System.out.println("Error" + ex.getErrorCode());
                    }

                    return;
                } else {
                    JOptionPane.showMessageDialog(this, "this ID isn't exist please choose another one", "Sorry", 2);
                }

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel44KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel44KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel44KeyPressed

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel45MouseClicked

    private void jLabel45KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel45KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel45KeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            AdminPortal f = new AdminPortal();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            AdminLoginForm f = new AdminLoginForm();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String check_id;
        check_id = jTextField63.getText();
        if ("".equals(jTextField63.getText()) || "".equals(jTextField79.getText()) || "".equals(jTextField59.getText()) || "".equals(jTextField16.getText())) {
            JOptionPane.showMessageDialog(this, "Please search about your Nurse before press \"Delete\"", "Sorry", 2);
            return;
        }
        try {
            java.sql.Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt1 = con1.prepareStatement("select * from nurse");
            ResultSet set = stmt1.executeQuery();
            while (set.next()) {
                String id = set.getString("nurse_id");

                if (check_id.equals(id)) {
                    try {
                        java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
                        PreparedStatement stmt = con.prepareStatement("delete from nurse where nurse_id=?");
                        stmt.setInt(1, Integer.parseInt(check_id));
                        stmt.executeUpdate();
                        JOptionPane.showMessageDialog(null, "delete successfully", "done", JOptionPane.PLAIN_MESSAGE);
                        jTextField82.setText("");
                        jTextField81.setText("");
                        jTextField24.setText("");
                        jTextField80.setText("");
                        jTextField57.setText("");
                        jTextField58.setText("");
                        jTextField62.setText("");
                        jTextField59.setText("");
                        jTextField79.setText("");
                        jTextField16.setText("");
                        jComboBox13.setSelectedIndex(0);
                        jComboBox5.setSelectedIndex(0);
                    } catch (SQLException ex) {
                        JOptionPane.showConfirmDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
                        System.out.println("Error" + ex.getErrorCode());
                    }
                    return;
                } else {
                    JOptionPane.showMessageDialog(this, "this ID isn't exist please choose another one", "Sorry", 2);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jLabel59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel59MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel59MouseClicked

    private void jLabel59KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel59KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel59KeyPressed

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel60MouseClicked

    private void jLabel60KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel60KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel60KeyPressed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            AdminPortal f = new AdminPortal();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            AdminLoginForm f = new AdminLoginForm();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from nurse");
            ResultSet set = stmt.executeQuery();
            String check_id;
            String id = "";
            check_id = jTextField54.getText();
            while (set.next()) {
                id = set.getString("nurse_id");
                if (check_id.equals(id)) {
                    jTextField46.setText(set.getString("first_name"));
                    jTextField51.setText(set.getString("second_name"));
                    jTextField25.setText(set.getString("age"));
                    jTextField83.setText(set.getString("Ndate"));
                    jTextField48.setText(set.getString("address"));
                    jTextField49.setText(set.getString("city"));
                    jTextField53.setText(set.getString("phone"));
                    jTextField50.setText(set.getString("salary"));
                    jTextField69.setText(set.getString("specialist"));
                    jTextField17.setText(set.getString("ward_id"));
                    if ("Male".equals(set.getString("gender"))) {
                        jComboBox14.setSelectedIndex(1);
                    } else {
                        jComboBox14.setSelectedIndex(2);
                    }
                    if ("Single".equals(set.getString("Nstatus"))) {
                        jComboBox7.setSelectedIndex(2);
                    } else {
                        jComboBox7.setSelectedIndex(1);
                    }
                    break;
                }
            }
            if (check_id.equals("")) {
                JOptionPane.showMessageDialog(null, "Please, enter an ID to search about its Nurse", "Sorry", 2);
            } else if (!check_id.equals(id)) {
                JOptionPane.showMessageDialog(null, "this ID doesn't exist", "wrong", 0);
                jTextField46.setText("");
                jTextField51.setText("");
                jTextField25.setText("");
                jTextField83.setText("");
                jTextField48.setText("");
                jTextField49.setText("");
                jTextField53.setText("");
                jTextField50.setText("");
                jTextField69.setText("");
                jTextField17.setText("");
                jComboBox14.setSelectedIndex(0);
                jComboBox7.setSelectedIndex(0);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel62MouseClicked

    private void jLabel62KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel62KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel62KeyPressed

    private void jLabel63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel63MouseClicked

    private void jLabel63KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel63KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel63KeyPressed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            AdminPortal f = new AdminPortal();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            AdminLoginForm f = new AdminLoginForm();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from nurse");
            ResultSet set = stmt.executeQuery();
            String check_id;
            String id = "";
            check_id = jTextField63.getText();
            while (set.next()) {
                id = set.getString("nurse_id");
                if (check_id.equals(id)) {
                    jTextField82.setText(set.getString("first_name"));
                    jTextField81.setText(set.getString("second_name"));
                    jTextField24.setText(set.getString("age"));
                    jTextField80.setText(set.getString("Ndate"));
                    jTextField57.setText(set.getString("address"));
                    jTextField58.setText(set.getString("city"));
                    jTextField62.setText(set.getString("phone"));
                    jTextField59.setText(set.getString("salary"));
                    jTextField79.setText(set.getString("specialist"));
                    jTextField16.setText(set.getString("ward_id"));
                    if ("Male".equals(set.getString("gender"))) {
                        jComboBox13.setSelectedIndex(1);
                    } else {
                        jComboBox13.setSelectedIndex(2);
                    }
                    if ("Single".equals(set.getString("Nstatus"))) {
                        jComboBox5.setSelectedIndex(2);
                    } else {
                        jComboBox5.setSelectedIndex(1);
                    }
                    break;
                }

            }

            if (check_id.equals("")) {
                JOptionPane.showMessageDialog(null, "Please, enter an ID to search about its Nurse", "Sorry", 2);
            } else if (!check_id.equals(id)) {
                JOptionPane.showMessageDialog(null, "this ID doesn't exist", "wrong", 0);
                jTextField82.setText("");
                jTextField81.setText("");
                jTextField24.setText("");
                jTextField80.setText("");
                jTextField57.setText("");
                jTextField58.setText("");
                jTextField62.setText("");
                jTextField59.setText("");
                jTextField79.setText("");
                jTextField16.setText("");
                jComboBox13.setSelectedIndex(0);
                jComboBox5.setSelectedIndex(0);

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from nurse");
            ResultSet set = stmt.executeQuery();
            String check_id;
            String id = "";
            check_id = jTextField45.getText();
            while (set.next()) {
                id = set.getString("nurse_id");
                if (check_id.equals(id)) {
                    jTextField78.setText(set.getString("first_name"));
                    jTextField77.setText(set.getString("second_name"));
                    jTextField23.setText(set.getString("age"));
                    jTextField76.setText(set.getString("Ndate"));
                    jTextField29.setText(set.getString("address"));
                    jTextField39.setText(set.getString("city"));
                    jTextField44.setText(set.getString("phone"));
                    jTextField41.setText(set.getString("salary"));
                    jTextField75.setText(set.getString("specialist"));
                    jTextField15.setText(set.getString("ward_id"));
                    if ("Male".equals(set.getString("gender"))) {
                        jComboBox12.setSelectedIndex(1);
                    } else {
                        jComboBox12.setSelectedIndex(2);
                    }
                    if ("Single".equals(set.getString("Nstatus"))) {
                        jComboBox3.setSelectedIndex(2);
                    } else {
                        jComboBox3.setSelectedIndex(1);
                    }
                    break;
                }

            }

            if (check_id.equals("")) {
                JOptionPane.showMessageDialog(null, "Please, enter an ID to search about its Nurse", "Sorry", 2);
                jTextField78.setText("");
                jTextField77.setText("");
                jTextField23.setText("");
                jTextField76.setText("");
                jTextField29.setText("");
                jTextField39.setText("");
                jTextField44.setText("");
                jTextField41.setText("");
                jTextField75.setText("");
                jTextField15.setText("");
                jComboBox12.setSelectedIndex(0);
                jComboBox3.setSelectedIndex(0);
            } else if (!check_id.equals(id)) {
                JOptionPane.showMessageDialog(null, "this ID doesn't exist", "wrong", 0);
                jTextField78.setText("");
                jTextField77.setText("");
                jTextField23.setText("");
                jTextField76.setText("");
                jTextField29.setText("");
                jTextField39.setText("");
                jTextField44.setText("");
                jTextField41.setText("");
                jTextField75.setText("");
                jTextField15.setText("");
                jComboBox12.setSelectedIndex(0);
                jComboBox3.setSelectedIndex(0);

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jTextField72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField72ActionPerformed

    private void jTextField75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField75ActionPerformed

    private void jTextField79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField79ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField79ActionPerformed

    private void jTextField69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField69ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from nurse");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("Nurse ID");
            dm.addColumn("First Name");
            dm.addColumn("Second Name");
            dm.addColumn("Address");
            dm.addColumn("Age");
            dm.addColumn("Status");
            dm.addColumn("Gender");
            dm.addColumn("Phone");
            dm.addColumn("City");
            dm.addColumn("Salary");
            dm.addColumn("Specialist");
            dm.addColumn("Date");
            dm.addColumn("Ward Number");
            while (set.next()) {
                String r[] = {set.getString(1), set.getString(2),
                    set.getString(3), set.getString(4),
                    set.getString(5), set.getString(6), set.getString(7),
                    set.getString(8), set.getString(9), set.getString(10),
                    set.getString(11), set.getString(12), set.getString(13)};
                dm.addRow(r);
            }
            jTable1.setModel(dm);
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(this, "Please, review the user guide you made something wrong", "Sorry", 3);
            System.out.println("Error" + ex.getErrorCode());
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NurseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NurseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NurseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NurseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NurseDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField83;
    // End of variables declaration//GEN-END:variables
}
