/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import Receptionist.*;
import admin.*;
import com.mysql.jdbc.Connection;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.DefaultMenuLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahmoud160312
 */
public class WardDetails extends javax.swing.JFrame {

    /**
     * Creates new form IndoorPatient
     */
    public WardDetails() {
        initComponents();
        CenteredFrame(this);

    }

    public void CenteredFrame(javax.swing.JFrame objFrame) {
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        Change = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        nurse_idfield = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        ward1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        secondnamefield = new javax.swing.JTextField();
        firstnamefield = new javax.swing.JTextField();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel95 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        nurseid2field = new javax.swing.JTextField();
        jScrollPane11 = new javax.swing.JScrollPane();
        ward2 = new javax.swing.JTable();
        Change5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        secondnamefield2 = new javax.swing.JTextField();
        firstnamefield2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel94 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        nurseid3field = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        ward3 = new javax.swing.JTable();
        Change6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        secondname3field = new javax.swing.JTextField();
        firstname3field = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        ward4 = new javax.swing.JTable();
        jLabel61 = new javax.swing.JLabel();
        nurseid4field = new javax.swing.JTextField();
        firstname4field = new javax.swing.JTextField();
        Change7 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        secondname4field = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel88 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        nurseid5field = new javax.swing.JTextField();
        firstname5field = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        ward5 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        Change8 = new javax.swing.JButton();
        secondname5field = new javax.swing.JTextField();
        jLabel92 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 204));
        jLabel20.setText("Nurse ID:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(170, 420, 110, 30);

        Change.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Change.setForeground(new java.awt.Color(51, 102, 255));
        Change.setText("View");
        Change.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeActionPerformed(evt);
            }
        });
        jPanel1.add(Change);
        Change.setBounds(570, 450, 127, 39);

        jPanel13.setBackground(new java.awt.Color(0, 153, 204));
        jPanel13.setLayout(null);

        jLabel70.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("Ward 1 Details");
        jPanel13.add(jLabel70);
        jLabel70.setBounds(20, 0, 230, 70);

        jLabel71.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("Logout");
        jLabel71.setToolTipText("");
        jLabel71.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.add(jLabel71);
        jLabel71.setBounds(830, 50, 50, 20);

        jLabel72.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("Home");
        jLabel72.setToolTipText("");
        jLabel72.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.add(jLabel72);
        jLabel72.setBounds(780, 50, 50, 20);

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton28);
        jButton28.setBounds(790, 20, 30, 30);

        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton29);
        jButton29.setBounds(840, 20, 30, 30);

        jPanel1.add(jPanel13);
        jPanel13.setBounds(10, 50, 910, 70);

        nurse_idfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nurse_idfieldMouseClicked(evt);
            }
        });
        nurse_idfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurse_idfieldActionPerformed(evt);
            }
        });
        jPanel1.add(nurse_idfield);
        nurse_idfield.setBounds(280, 420, 180, 30);

        ward1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "First Name", "Second Name", "Age", "Gender", "Status", "Date", "Address", "City", "Phone", "illness"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane12.setViewportView(ward1);
        if (ward1.getColumnModel().getColumnCount() > 0) {
            ward1.getColumnModel().getColumn(2).setPreferredWidth(90);
            ward1.getColumnModel().getColumn(7).setPreferredWidth(150);
        }

        jPanel1.add(jScrollPane12);
        jScrollPane12.setBounds(0, 150, 910, 210);

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 360, 910, 30);

        secondnamefield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondnamefieldMouseClicked(evt);
            }
        });
        secondnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondnamefieldActionPerformed(evt);
            }
        });
        jPanel1.add(secondnamefield);
        secondnamefield.setBounds(280, 500, 180, 30);

        firstnamefield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstnamefieldMouseClicked(evt);
            }
        });
        firstnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefieldActionPerformed(evt);
            }
        });
        jPanel1.add(firstnamefield);
        firstnamefield.setBounds(280, 460, 180, 30);

        jLabel96.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(0, 153, 204));
        jLabel96.setText("First Name:");
        jPanel1.add(jLabel96);
        jLabel96.setBounds(170, 460, 110, 30);

        jLabel97.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(0, 153, 204));
        jLabel97.setText("Second Name:");
        jPanel1.add(jLabel97);
        jLabel97.setBounds(170, 500, 110, 30);

        jTabbedPane1.addTab("Ward 1", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel14.setBackground(new java.awt.Color(0, 153, 204));
        jPanel14.setLayout(null);

        jLabel73.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("Ward 2 Details");
        jPanel14.add(jLabel73);
        jLabel73.setBounds(20, 0, 230, 70);

        jLabel74.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel74.setText("Logout");
        jLabel74.setToolTipText("");
        jLabel74.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.add(jLabel74);
        jLabel74.setBounds(830, 50, 50, 20);

        jLabel75.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("Home");
        jLabel75.setToolTipText("");
        jLabel75.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.add(jLabel75);
        jLabel75.setBounds(780, 50, 50, 20);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton13);
        jButton13.setBounds(790, 20, 30, 30);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton17);
        jButton17.setBounds(840, 20, 30, 30);

        jPanel2.add(jPanel14);
        jPanel14.setBounds(10, 50, 910, 70);

        jLabel95.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(0, 153, 204));
        jLabel95.setText("Second Name:");
        jPanel2.add(jLabel95);
        jLabel95.setBounds(170, 500, 110, 30);

        jLabel25.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 204));
        jLabel25.setText("Nurse ID:");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(170, 420, 110, 30);

        nurseid2field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nurseid2fieldMouseClicked(evt);
            }
        });
        nurseid2field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseid2fieldActionPerformed(evt);
            }
        });
        jPanel2.add(nurseid2field);
        nurseid2field.setBounds(280, 420, 180, 30);

        ward2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "First Name", "Second Name", "Age", "Gender", "Status", "Date", "Address", "City", "Phone", "illness"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane11.setViewportView(ward2);
        if (ward2.getColumnModel().getColumnCount() > 0) {
            ward2.getColumnModel().getColumn(7).setPreferredWidth(150);
        }

        jPanel2.add(jScrollPane11);
        jScrollPane11.setBounds(0, 150, 910, 210);

        Change5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Change5.setForeground(new java.awt.Color(51, 102, 255));
        Change5.setText("View");
        Change5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Change5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change5ActionPerformed(evt);
            }
        });
        jPanel2.add(Change5);
        Change5.setBounds(570, 450, 127, 39);

        jPanel7.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7);
        jPanel7.setBounds(0, 360, 910, 30);

        jLabel66.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 153, 204));
        jLabel66.setText("First Name:");
        jPanel2.add(jLabel66);
        jLabel66.setBounds(170, 460, 110, 30);

        secondnamefield2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondnamefield2MouseClicked(evt);
            }
        });
        secondnamefield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondnamefield2ActionPerformed(evt);
            }
        });
        jPanel2.add(secondnamefield2);
        secondnamefield2.setBounds(280, 500, 180, 30);

        firstnamefield2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstnamefield2MouseClicked(evt);
            }
        });
        firstnamefield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnamefield2ActionPerformed(evt);
            }
        });
        jPanel2.add(firstnamefield2);
        firstnamefield2.setBounds(280, 460, 180, 30);

        jTabbedPane1.addTab("Ward 2", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel15.setBackground(new java.awt.Color(0, 153, 204));
        jPanel15.setLayout(null);

        jLabel76.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel76.setText("Ward 3 Details");
        jPanel15.add(jLabel76);
        jLabel76.setBounds(20, 0, 230, 70);

        jLabel77.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel77.setText("Logout");
        jLabel77.setToolTipText("");
        jLabel77.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.add(jLabel77);
        jLabel77.setBounds(830, 50, 50, 20);

        jLabel78.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel78.setText("Home");
        jLabel78.setToolTipText("");
        jLabel78.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.add(jLabel78);
        jLabel78.setBounds(780, 50, 50, 20);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton18);
        jButton18.setBounds(790, 20, 30, 30);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton14);
        jButton14.setBounds(840, 20, 30, 30);

        jPanel3.add(jPanel15);
        jPanel15.setBounds(10, 50, 910, 70);

        jLabel94.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(0, 153, 204));
        jLabel94.setText("Second Name:");
        jPanel3.add(jLabel94);
        jLabel94.setBounds(170, 500, 110, 30);

        jLabel65.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 153, 204));
        jLabel65.setText("First Name:");
        jPanel3.add(jLabel65);
        jLabel65.setBounds(170, 460, 110, 30);

        jLabel49.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 153, 204));
        jLabel49.setText("Nurse ID:");
        jPanel3.add(jLabel49);
        jLabel49.setBounds(170, 420, 110, 30);

        nurseid3field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nurseid3fieldMouseClicked(evt);
            }
        });
        nurseid3field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseid3fieldActionPerformed(evt);
            }
        });
        jPanel3.add(nurseid3field);
        nurseid3field.setBounds(280, 420, 180, 30);

        ward3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "First Name", "Second Name", "Age", "Gender", "Status", "Date", "Address", "City", "Phone", "illness"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane10.setViewportView(ward3);
        if (ward3.getColumnModel().getColumnCount() > 0) {
            ward3.getColumnModel().getColumn(7).setPreferredWidth(150);
        }

        jPanel3.add(jScrollPane10);
        jScrollPane10.setBounds(0, 150, 910, 210);

        Change6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Change6.setForeground(new java.awt.Color(51, 102, 255));
        Change6.setText("View");
        Change6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Change6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change6ActionPerformed(evt);
            }
        });
        jPanel3.add(Change6);
        Change6.setBounds(570, 450, 127, 39);

        jPanel8.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel8);
        jPanel8.setBounds(0, 360, 910, 30);

        secondname3field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondname3fieldMouseClicked(evt);
            }
        });
        secondname3field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondname3fieldActionPerformed(evt);
            }
        });
        jPanel3.add(secondname3field);
        secondname3field.setBounds(280, 500, 180, 30);

        firstname3field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstname3fieldMouseClicked(evt);
            }
        });
        firstname3field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstname3fieldActionPerformed(evt);
            }
        });
        jPanel3.add(firstname3field);
        firstname3field.setBounds(280, 460, 180, 30);

        jTabbedPane1.addTab("Ward 3", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel64.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 153, 204));
        jLabel64.setText("First Name:");
        jPanel4.add(jLabel64);
        jLabel64.setBounds(170, 460, 110, 30);

        jLabel93.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(0, 153, 204));
        jLabel93.setText("Second Name:");
        jPanel4.add(jLabel93);
        jLabel93.setBounds(170, 500, 110, 30);

        jPanel16.setBackground(new java.awt.Color(0, 153, 204));
        jPanel16.setLayout(null);

        jLabel79.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel79.setText("Ward 4 Details");
        jPanel16.add(jLabel79);
        jLabel79.setBounds(20, 0, 230, 70);

        jLabel80.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel80.setText("Logout");
        jLabel80.setToolTipText("");
        jLabel80.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.add(jLabel80);
        jLabel80.setBounds(830, 50, 50, 20);

        jLabel81.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel81.setText("Home");
        jLabel81.setToolTipText("");
        jLabel81.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.add(jLabel81);
        jLabel81.setBounds(780, 50, 50, 20);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton19);
        jButton19.setBounds(790, 20, 30, 30);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton20);
        jButton20.setBounds(840, 20, 30, 30);

        jPanel4.add(jPanel16);
        jPanel16.setBounds(10, 50, 910, 70);

        ward4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "First Name", "Second Name", "Age", "Gender", "Status", "Date", "Address", "City", "Phone", "illness"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(ward4);
        if (ward4.getColumnModel().getColumnCount() > 0) {
            ward4.getColumnModel().getColumn(7).setPreferredWidth(150);
        }

        jPanel4.add(jScrollPane7);
        jScrollPane7.setBounds(0, 150, 910, 210);

        jLabel61.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 153, 204));
        jLabel61.setText("Nurse ID:");
        jPanel4.add(jLabel61);
        jLabel61.setBounds(170, 420, 110, 30);

        nurseid4field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nurseid4fieldMouseClicked(evt);
            }
        });
        nurseid4field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseid4fieldActionPerformed(evt);
            }
        });
        jPanel4.add(nurseid4field);
        nurseid4field.setBounds(280, 420, 180, 30);

        firstname4field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstname4fieldMouseClicked(evt);
            }
        });
        firstname4field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstname4fieldActionPerformed(evt);
            }
        });
        jPanel4.add(firstname4field);
        firstname4field.setBounds(280, 460, 180, 30);

        Change7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Change7.setForeground(new java.awt.Color(51, 102, 255));
        Change7.setText("View");
        Change7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Change7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change7ActionPerformed(evt);
            }
        });
        jPanel4.add(Change7);
        Change7.setBounds(570, 450, 127, 39);

        jPanel9.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel9);
        jPanel9.setBounds(0, 360, 910, 30);

        secondname4field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondname4fieldMouseClicked(evt);
            }
        });
        secondname4field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondname4fieldActionPerformed(evt);
            }
        });
        jPanel4.add(secondname4field);
        secondname4field.setBounds(280, 500, 180, 30);

        jTabbedPane1.addTab("Ward 4", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jPanel17.setBackground(new java.awt.Color(0, 153, 204));
        jPanel17.setLayout(null);

        jLabel82.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel82.setText("Ward 5 Details");
        jPanel17.add(jLabel82);
        jLabel82.setBounds(20, 0, 230, 70);

        jLabel83.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel83.setText("Logout");
        jLabel83.setToolTipText("");
        jLabel83.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel17.add(jLabel83);
        jLabel83.setBounds(830, 50, 50, 20);

        jLabel84.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel84.setText("Home");
        jLabel84.setToolTipText("");
        jLabel84.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel17.add(jLabel84);
        jLabel84.setBounds(780, 50, 50, 20);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/home icon.jpg"))); // NOI18N
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton21);
        jButton21.setBounds(790, 20, 30, 30);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hds/photo/logout icon.jpg"))); // NOI18N
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton22);
        jButton22.setBounds(840, 20, 30, 30);

        jPanel5.add(jPanel17);
        jPanel17.setBounds(10, 50, 910, 70);

        jLabel88.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(0, 153, 204));
        jLabel88.setText("Nurse ID:");
        jPanel5.add(jLabel88);
        jLabel88.setBounds(170, 420, 110, 30);

        jLabel91.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(0, 153, 204));
        jLabel91.setText("First Name:");
        jPanel5.add(jLabel91);
        jLabel91.setBounds(170, 460, 110, 30);

        nurseid5field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nurseid5fieldMouseClicked(evt);
            }
        });
        nurseid5field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseid5fieldActionPerformed(evt);
            }
        });
        jPanel5.add(nurseid5field);
        nurseid5field.setBounds(280, 420, 180, 30);

        firstname5field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstname5fieldMouseClicked(evt);
            }
        });
        firstname5field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstname5fieldActionPerformed(evt);
            }
        });
        jPanel5.add(firstname5field);
        firstname5field.setBounds(280, 460, 180, 30);

        ward5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "First Name", "Second Name", "Age", "Gender", "Status", "Date", "Address", "City", "Phone", "illness"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane9.setViewportView(ward5);
        if (ward5.getColumnModel().getColumnCount() > 0) {
            ward5.getColumnModel().getColumn(7).setPreferredWidth(150);
        }

        jPanel5.add(jScrollPane9);
        jScrollPane9.setBounds(0, 150, 910, 210);

        jPanel10.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel10);
        jPanel10.setBounds(0, 360, 910, 30);

        Change8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Change8.setForeground(new java.awt.Color(51, 102, 255));
        Change8.setText("View");
        Change8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Change8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change8ActionPerformed(evt);
            }
        });
        jPanel5.add(Change8);
        Change8.setBounds(570, 450, 127, 39);

        secondname5field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondname5fieldMouseClicked(evt);
            }
        });
        secondname5field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondname5fieldActionPerformed(evt);
            }
        });
        jPanel5.add(secondname5field);
        secondname5field.setBounds(280, 500, 180, 30);

        jLabel92.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(0, 153, 204));
        jLabel92.setText("Second Name:");
        jPanel5.add(jLabel92);
        jLabel92.setBounds(170, 500, 110, 30);

        jTabbedPane1.addTab("Ward 5", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstname5fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstname5fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstname5fieldActionPerformed

    private void firstname5fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstname5fieldMouseClicked

    }//GEN-LAST:event_firstname5fieldMouseClicked

    private void nurseid5fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseid5fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nurseid5fieldActionPerformed

    private void nurseid5fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nurseid5fieldMouseClicked

    }//GEN-LAST:event_nurseid5fieldMouseClicked

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            AdminLoginForm f = new AdminLoginForm();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            AdminPortal f = new AdminPortal();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void firstname4fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstname4fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstname4fieldActionPerformed

    private void firstname4fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstname4fieldMouseClicked

    }//GEN-LAST:event_firstname4fieldMouseClicked

    private void nurseid4fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseid4fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nurseid4fieldActionPerformed

    private void nurseid4fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nurseid4fieldMouseClicked

    }//GEN-LAST:event_nurseid4fieldMouseClicked

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            AdminLoginForm f = new AdminLoginForm();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            AdminPortal f = new AdminPortal();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void nurseid3fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseid3fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nurseid3fieldActionPerformed

    private void nurseid3fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nurseid3fieldMouseClicked

    }//GEN-LAST:event_nurseid3fieldMouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            AdminLoginForm f = new AdminLoginForm();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            AdminPortal f = new AdminPortal();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void Change5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change5ActionPerformed
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from patient where ward_n=2");
            PreparedStatement stmt2 = con.prepareStatement("select * from nurse where ward_id=2");

            ResultSet set = stmt.executeQuery();
            ResultSet set2 = stmt2.executeQuery();

            DefaultTableModel dm = new DefaultTableModel();

            dm.addColumn("patient_id");
            dm.addColumn("first_name");
            dm.addColumn("second_name");
            dm.addColumn("age");
            dm.addColumn("address");
            dm.addColumn("gender");
            dm.addColumn("phone");
            dm.addColumn("city");
            dm.addColumn("pstatus");
            dm.addColumn("pdate");
            dm.addColumn("illness");

            while (set.next()) {

                String r[] = {set.getString(1), set.getString(2),
                    set.getString(3), set.getString(4),
                    set.getString(5), set.getString(6), set.getString(7),
                    set.getString(8), set.getString(9), set.getString(10),
                    set.getString(11), set.getString(12)};
                dm.addRow(r);
            }
            ward2.setModel(dm);

            //************* exsecute search in nurse table***********
            String nurse_id = "", first_name = "", second_name = "", checkid = "";

            while (set2.next()) {

                nurse_id = set2.getString("nurse_id");
                first_name = set2.getString("first_name");
                second_name = set2.getString("second_name");

                //***********************************************************
            }
            nurseid2field.setText(nurse_id);
            firstnamefield2.setText(first_name);
            secondnamefield2.setText(second_name);

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }
    }//GEN-LAST:event_Change5ActionPerformed

    private void nurseid2fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseid2fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nurseid2fieldActionPerformed

    private void nurseid2fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nurseid2fieldMouseClicked

    }//GEN-LAST:event_nurseid2fieldMouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            AdminLoginForm f = new AdminLoginForm();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            AdminPortal f = new AdminPortal();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void nurse_idfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurse_idfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nurse_idfieldActionPerformed

    private void nurse_idfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nurse_idfieldMouseClicked

    }//GEN-LAST:event_nurse_idfieldMouseClicked

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to logout", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {

            AdminLoginForm f = new AdminLoginForm();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        int replay = JOptionPane.showConfirmDialog(this, "are you sure you want to back to Home Page", "", JOptionPane.YES_NO_OPTION, 1);
        if (replay == JOptionPane.YES_OPTION) {
            AdminPortal f = new AdminPortal();
            this.setVisible(false);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton28ActionPerformed

    private void ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeActionPerformed
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from patient where ward_n=1");
            PreparedStatement stmt2 = con.prepareStatement("select * from nurse where ward_id=1");

            ResultSet set = stmt.executeQuery();
            ResultSet set2 = stmt2.executeQuery();

            DefaultTableModel dm = new DefaultTableModel();

            dm.addColumn("patient_id");
            dm.addColumn("first_name");
            dm.addColumn("second_name");
            dm.addColumn("age");
            dm.addColumn("address");
            dm.addColumn("gender");
            dm.addColumn("phone");
            dm.addColumn("city");
            dm.addColumn("pstatus");
            dm.addColumn("pdate");
            dm.addColumn("illness");

            while (set.next()) {

                String r[] = {set.getString(1), set.getString(2),
                    set.getString(3), set.getString(4),
                    set.getString(5), set.getString(6), set.getString(7),
                    set.getString(8), set.getString(9), set.getString(10),
                    set.getString(11), set.getString(12)};
                dm.addRow(r);
            }
            ward1.setModel(dm);

            //************* exsecute search in nurse table***********
            String nurse_id = "", first_name = "", second_name = "", checkid = "";

            while (set2.next()) {

                nurse_id = set2.getString("nurse_id");
                first_name = set2.getString("first_name");
                second_name = set2.getString("second_name");

                //***********************************************************
            }
            nurse_idfield.setText(nurse_id);
            firstnamefield.setText(first_name);
            secondnamefield.setText(second_name);

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }


    }//GEN-LAST:event_ChangeActionPerformed

    private void Change6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change6ActionPerformed
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from patient where ward_n=3");
            PreparedStatement stmt2 = con.prepareStatement("select * from nurse where ward_id=3");

            ResultSet set = stmt.executeQuery();
            ResultSet set2 = stmt2.executeQuery();

            DefaultTableModel dm = new DefaultTableModel();

            dm.addColumn("patient_id");
            dm.addColumn("first_name");
            dm.addColumn("second_name");
            dm.addColumn("age");
            dm.addColumn("address");
            dm.addColumn("gender");
            dm.addColumn("phone");
            dm.addColumn("city");
            dm.addColumn("pstatus");
            dm.addColumn("pdate");
            dm.addColumn("illness");

            while (set.next()) {

                String r[] = {set.getString(1), set.getString(2),
                    set.getString(3), set.getString(4),
                    set.getString(5), set.getString(6), set.getString(7),
                    set.getString(8), set.getString(9), set.getString(10),
                    set.getString(11), set.getString(12)};
                dm.addRow(r);
            }
            ward3.setModel(dm);

            //************* exsecute search in nurse table***********
            String nurse_id = "", first_name = "", second_name = "", checkid = "";

            while (set2.next()) {

                nurse_id = set2.getString("nurse_id");
                first_name = set2.getString("first_name");
                second_name = set2.getString("second_name");

                //***********************************************************
            }
            nurseid3field.setText(nurse_id);
            firstname3field.setText(first_name);
            secondname3field.setText(second_name);

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }
    }//GEN-LAST:event_Change6ActionPerformed

    private void Change7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change7ActionPerformed
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from patient where ward_n=4");
            PreparedStatement stmt2 = con.prepareStatement("select * from nurse where ward_id=4");

            ResultSet set = stmt.executeQuery();
            ResultSet set2 = stmt2.executeQuery();

            DefaultTableModel dm = new DefaultTableModel();

            dm.addColumn("patient_id");
            dm.addColumn("first_name");
            dm.addColumn("second_name");
            dm.addColumn("age");
            dm.addColumn("address");
            dm.addColumn("gender");
            dm.addColumn("phone");
            dm.addColumn("city");
            dm.addColumn("pstatus");
            dm.addColumn("pdate");
            dm.addColumn("illness");

            while (set.next()) {

                String r[] = {set.getString(1), set.getString(2),
                    set.getString(3), set.getString(4),
                    set.getString(5), set.getString(6), set.getString(7),
                    set.getString(8), set.getString(9), set.getString(10),
                    set.getString(11), set.getString(12)};
                dm.addRow(r);
            }
            ward4.setModel(dm);

            //************* exsecute search in nurse table***********
            String nurse_id = "", first_name = "", second_name = "", checkid = "";

            while (set2.next()) {

                nurse_id = set2.getString("nurse_id");
                first_name = set2.getString("first_name");
                second_name = set2.getString("second_name");

                //***********************************************************
            }
            nurseid4field.setText(nurse_id);
            firstname4field.setText(first_name);
            secondname4field.setText(second_name);

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }

    }//GEN-LAST:event_Change7ActionPerformed

    private void Change8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change8ActionPerformed
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hdbs", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from patient where ward_n=5");
            PreparedStatement stmt2 = con.prepareStatement("select * from nurse where ward_id=5");

            ResultSet set = stmt.executeQuery();
            ResultSet set2 = stmt2.executeQuery();

            DefaultTableModel dm = new DefaultTableModel();

            dm.addColumn("patient_id");
            dm.addColumn("first_name");
            dm.addColumn("second_name");
            dm.addColumn("age");
            dm.addColumn("address");
            dm.addColumn("gender");
            dm.addColumn("phone");
            dm.addColumn("city");
            dm.addColumn("pstatus");
            dm.addColumn("pdate");
            dm.addColumn("illness");

            while (set.next()) {

                String r[] = {set.getString(1), set.getString(2),
                    set.getString(3), set.getString(4),
                    set.getString(5), set.getString(6), set.getString(7),
                    set.getString(8), set.getString(9), set.getString(10),
                    set.getString(11), set.getString(12)};
                dm.addRow(r);
            }
            ward5.setModel(dm);

            //************* exsecute search in nurse table***********
            String nurse_id = "", first_name = "", second_name = "", checkid = "";

            while (set2.next()) {

                nurse_id = set2.getString("nurse_id");
                first_name = set2.getString("first_name");
                second_name = set2.getString("second_name");

                //***********************************************************
            }
            nurseid5field.setText(nurse_id);
            firstname5field.setText(first_name);
            secondname5field.setText(second_name);

        } catch (SQLException ex) {
            System.out.println("Error" + ex.getErrorCode());
        }
    }//GEN-LAST:event_Change8ActionPerformed

    private void secondname5fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondname5fieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_secondname5fieldMouseClicked

    private void secondname5fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondname5fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondname5fieldActionPerformed

    private void secondname4fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondname4fieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_secondname4fieldMouseClicked

    private void secondname4fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondname4fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondname4fieldActionPerformed

    private void secondname3fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondname3fieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_secondname3fieldMouseClicked

    private void secondname3fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondname3fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondname3fieldActionPerformed

    private void firstname3fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstname3fieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_firstname3fieldMouseClicked

    private void firstname3fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstname3fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstname3fieldActionPerformed

    private void secondnamefield2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondnamefield2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_secondnamefield2MouseClicked

    private void secondnamefield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondnamefield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondnamefield2ActionPerformed

    private void firstnamefield2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefield2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield2MouseClicked

    private void firstnamefield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefield2ActionPerformed

    private void secondnamefieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondnamefieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_secondnamefieldMouseClicked

    private void secondnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondnamefieldActionPerformed

    private void firstnamefieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnamefieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefieldMouseClicked

    private void firstnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnamefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WardDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WardDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WardDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WardDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WardDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Change;
    private javax.swing.JButton Change5;
    private javax.swing.JButton Change6;
    private javax.swing.JButton Change7;
    private javax.swing.JButton Change8;
    private javax.swing.JTextField firstname3field;
    private javax.swing.JTextField firstname4field;
    private javax.swing.JTextField firstname5field;
    private javax.swing.JTextField firstnamefield;
    private javax.swing.JTextField firstnamefield2;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nurse_idfield;
    private javax.swing.JTextField nurseid2field;
    private javax.swing.JTextField nurseid3field;
    private javax.swing.JTextField nurseid4field;
    private javax.swing.JTextField nurseid5field;
    private javax.swing.JTextField secondname3field;
    private javax.swing.JTextField secondname4field;
    private javax.swing.JTextField secondname5field;
    private javax.swing.JTextField secondnamefield;
    private javax.swing.JTextField secondnamefield2;
    private javax.swing.JTable ward1;
    private javax.swing.JTable ward2;
    private javax.swing.JTable ward3;
    private javax.swing.JTable ward4;
    private javax.swing.JTable ward5;
    // End of variables declaration//GEN-END:variables
}
